mindee/doctr

doctr/models/__init__.py, doctr/models/core.py, doctr/models/detection/core.py, doctr/models/detection/differentiable_binarization.py, doctr/models/recognition/core.py, doctr/models/recognition/crnn.py, doctr/models/recognition/postprocessor.py, doctr/models/recognition/sar.py, doctr/models/utils.py, doctr/models/vgg.py, doctr/models/zoo.py, test/test_models.py
- renamed all model input_size constructor arg to input_shape
- added a cfg attribute to each model to be able to access its build parameters
- fixed DB post processing by adding safeguard against edge cases
- added credits for DB post processing
- fixed bias before BN in conv_sequence
- added model zoo for full OCR predictors
- fixed model export unittest (cf. #27)
- simplified recognition architecture passing down the vocab (rather than num_classes + label_mapping)
- reflected changes on unittests
- avoids embedding recreation in recognition architectures
Successfully merging this PR will close #53
=> feat: Added a full pretrained predictor for upcoming release

test/test_models.py
This PR simply updates the URL from the pretrained loading unittest by switching from GoFile to github release attachments.
=> test: Switched test URL to Github hosting

test/test_models.py
- updates the input size for the post processor unittest (from 116 to 119 to be the same as current models)
- replaced a useless assertion that was testing whether each word is shorter than the vocab with a test checking that each character is in the vocab
=> test: Improved unittests for recognition post processors

doctr/models/detection/core.py, doctr/models/recognition/core.py, doctr/models/recognition/postprocessor.py, doctr/models/recognition/sar.py
- removed all `tf.shape` in favor of the better `.shape` attribute of tensors
- fixed resizing for recognition crop for all edge cases
Successfully merging this will close #72 
=> fix: Fixed edge case of recognition crop resizing

doctr/documents/reader.py, test/test_documents.py
- added specific image reading errors: as pointed out by @mohamedmindee, `cv2.imread` yields a `None` whether the file is incorrectly located or of the wrong type, which is now fixed
- added specific unittests to check the new behaviour
=> feat: Added clearer errors for incorrect image reading

.github/ISSUE_TEMPLATE/bug_report.md, scripts/collect_env.py
- added an environment collection script
- updated bug report template to suggest users to use the script
For reference, here is my output:
```
Collecting environment information...
DocTR version: 0.1.0a0
TensorFlow version: 2.4.1
OS: Ubuntu 20.04.2 LTS
Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: GeForce RTX 2070 with Max-Q Design
Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5 …
```
=> chore: Added environment collection script

docs/requirements.txt
This PR simply fixes the sphinx requirement that is now troublesome since version 3.5.0. The bug has been reported but won't be in stable version before next release, hence the version constraint.
=> docs: Fixed sphinx requirements

doctr/models/detection/differentiable_binarization.py, doctr/models/export.py, doctr/models/recognition/crnn.py, doctr/models/recognition/sar.py, doctr/models/resnet.py, doctr/models/utils.py, doctr/models/vgg.py, doctr/models/zoo.py, doctr/utils/visualization.py
- added examples in major functions/classes docstrings
- fixed the docstring of `doctr.models.utils.load_pretrained_params`
- added default value to `pretrained` arg in OCR predictors
=> docs: Added multiple examples in docstrings

doctr/models/utils.py, test/test_models_utils.py
- fixed the duplication of activation in conv_sequece in a specific case
- added unittest to check the fix
=> fix: Fixed activation duplication in conv_sequence

doctr/documents/elements.py, doctr/models/core.py, doctr/models/detection/core.py, doctr/models/detection/differentiable_binarization.py, doctr/models/preprocessor.py, doctr/models/recognition/core.py, doctr/models/recognition/sar.py, doctr/models/utils.py, doctr/utils/__init__.py, doctr/utils/repr.py, test/test_documents_elements.py, test/test_models.py, test/test_models_detection.py, test/test_models_recognition.py, test/test_models_utils.py
- added repr to all Elements
- added repr to preprocessors, postprocessors and models
Here is the repr of `ocr_db_crnn` for illustration:
```
OCRPredictor(
(det_predictor): DetectionPredictor(
(pre_processor): DetectionPreProcessor(output_size=(1024, 1024), mean=[0.5 0.5 0.5], std=[1. 1. 1.])
(model): DBNet(
(feat_extractor): IntermediateLayerGetter()
(fpn): FeaturePyramidNetwork(channels=128)
(probability_head): <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f9fb81ce070>
(threshold_head): <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f9fb81db100>
)
(post_processor): DBPostProcessor(box_thresh=0.1, max_candidates=1000)
)
(reco_predictor): RecognitionPredictor( …
```
=> feat: Added repr to elements

README.md, docs/source/models.rst
- adds a table for text detection models in the documentation (archi, input shape, num of params, recall, precision, fps)
- adds a table for text recognition models (archi, input shape, num of params, accuracy, fps)
- adds a reference to those tables in the README
Successfully merging this PR will close #94
=> docs: Added model zoo table in documentation

doctr/models/recognition/sar.py, test/test_models_recognition.py
Successfully merging this PR closes #71 , any feedback is welcome!
=> feat: add sar teacher forcing

doctr/models/recognition/sar.py
This is a fix for the PR #107: dense labels for teacher forcing were not padded to the length (max_lentgh + 1), and it was crashing the model. SAR is now operational for training. Any feedback is welcome !
=> fix: pad teacher forcing

doctr/models/recognition/sar.py
This PR repaces the url of the SAR pretrained model in the default cfgs
=> feat: Added pretrained weights for SAR

doctr/models/core.py, test/test_models.py
Following up on #118, this PR introduces the following modifications:
- fixed block building when there is no detection in the page
- added a corresponding unittest
=> fix: Fixed edge case of result export when there is no detection

doctr/utils/repr.py, test/test_documents_elements.py
- simplified empty child list repr of NestedObject
- adding a unittest to check this
Before this PR, the following snippet:
```
from doctr.documents.elements import Line
print(Line([], ((0, 0), (1, 1))))
```
would yield
```
Line(
(words): [
]
)
```
while now it yields
```
Line(
(words): []
)
```
=> feat: Simplified repr of NestedObject when they have an empty list of children

docs/build.sh
This PR fixes multi-version documentation build from CI. 
Currently, the CI has a shallow view of git history, so a `git checkout <HASH>` fails as the history is shallow. 
You can notice the `error: pathspec '571af3dc' did not match any file(s) known to git` error message in the doc deployment [action](https://github.com/mindee/doctr/runs/2096643999?check_suite_focus=true). The consequence of that, is that all versions of the doc that are deployed are the same: cf. https://mindee.github.io/doctr/
I added a `git fetch` to fix this.
=> docs: Fixed multi-versions doc build

doctr/utils/metrics.py, test/test_utils_metrics.py
This PR fixes iou intersection computation for edge cases (clipping by (0, inf) the right-left and bot-top arrays to ensure that intersection will be set to 0 when boxes are not overlapping)
=> fix: edge case intersection iou metric

docs/source/models.rst, doctr/models/recognition/core.py, doctr/models/recognition/sar.py, doctr/models/zoo.py, test/test_models_recognition.py
This PR implements the following:
- Benchmark results for 2 end to end models, 2 recognition models and 1 detection model
- set default input size for SAR to 32x128
- set default batch size for recognition task to 32
Any Feedback is welcome!
=> feat: add model perf + changed default cfgs

doctr/models/detection/differentiable_binarization.py, doctr/models/recognition/crnn.py, doctr/models/recognition/sar.py
- updated DBNet, CRNN & SAR to correctly size the kernel of the entire model
- used this to save checkpoints correctly that won't trigger annoying warnings like previously
(I checked the analyze script result and they are unchanged)
=> feat: Added proper kernel sizing to silence loading warnings

.github/workflows/pkg-upload.yaml
- removed CI to build conda since it cannot work for now as per #113
- fixed pypi upload job (renamed doctr to python-doctr before upload): each new release created on Github will trigger the publishing on pypi automatically
=> chore: Fixed CI pypi automatic publish upon release

docs/source/conf.py, docs/source/datasets.rst, docs/source/models.rst, docs/source/utils.rst, doctr/utils/metrics.py
- specified on which dataset the evaluation runs were conducted
- added disclaimer about the low dataset size
- added detailed explanation about metric computation for each task
Here is how the documentation renders for `OCRMetric`:
=> docs: Added documentation about model evaluation

README.md, doctr/models/core.py, doctr/models/zoo.py, scripts/analyze.py, scripts/evaluate.py, test/test_models.py
- switched OCRPredictor input to a list of pages and output to a `Document`
- updated unittests, usage instructions, documentation and scripts accordingly
Resolves #168 
=> refactor: Changed predictor call args to list of pages

README.md, docs/source/documents.rst, doctr/documents/reader.py, scripts/analyze.py, scripts/evaluate.py, test/test_documents_reader.py
- for PDF & images, added support of path (`str` or `pathlib.Path`)
- implemented a `DocumentFile` with class methods to read the doc from a single pdf, or from one or multiples images
- added unittests
- updated README
Breaking changes: deprecated `read_pdf_from_stream` since `read_pdf` now handles it natively
Resolves #166 
=> feat: Expanded support of file reading

README.md, doctr/utils/visualization.py
- added a scale arg in `visualize_page` that defines the longest side of the figure while preserving aspect ratio
- increased default value for better visual UX
- added analysis script visualization GIF in README
Here is how it renders now:
Resolves #167
=> feat: Added figure scale while preserving aspect ratio

doctr/utils/metrics.py, test/test_utils_metrics.py
- only performs the computation of IoU when both inputs are not zero-sized
- added unittests accordingly
=> fix: Fixed IoU computation for zero-sized inputs

demo/app.py, scripts/analyze.py, scripts/evaluate.py
When available GPU RAM memory is not available, and other edge cases, tensorflow raises a mysterious error `CUBLAS_STATUS_NOT_INITIALIZED`. To tackle this, this PR introduces the following modifications:
- added gpu memory growth for tensorflow in scripts and demo
- silenced tensorflow warning in `scripts/analyze.py`
=> fix: Added default TF gpu memory growth

doctr/datasets/loaders/detection.py, doctr/datasets/loaders/recognition.py
- fixes a typo in variable naming (indexes -> indices)
- fixes `os.listdir` being computed for each sample unnecessarily
=> fix: Fixed unnecessary os.listdir for each sample

docs/source/models.rst, doctr/models/zoo.py
This PR adds in the docs:
- FPS for each model, averaged on 1000 random tensors
- FPS for each end-to-end predictor, averaged on each dataset
Default batch size is now 128 for the recognition task in the predictor.
=> feat: add FPS in docs

references/recognition/train.py
This PR adds a /255 normalization (which was missing) when loading the validation recognition dataset in the training script.
=> fix: train recognition script, /255 validation dataset

doctr/models/core.py, test/test_models.py
This PR implements resolve_blocks inside DocumentBuilder:
Each document can be built using resolve_block=True (only works if resolve_line=True and both are set to False by default to lighten postprocessing), which will determine the blocks of the pages with a hierarchical clustering on the lines.
Computation time: highly insignificant, less than 0.01% of the prediction time for a light page and 0.1% for a dense page on GPU
Examples of detected blocks:
=> feat: add blocks detection

doctr/datasets/cord.py, doctr/datasets/funsd.py, scripts/evaluate.py
This PR fixes dtype (float --> int) for target["boxes"] of CORD and FUNSD, to avoid confusion between relative and absolute boxes.
=> fix: dtype target["boxes"] for CORD and FUNSD

doctr/documents/reader.py, test/test_documents_reader.py
- added appropriate error when read_pdf gets a path to inexisting file
=> feat: Improved error when read_pdf gets an incorrect path

doctr/models/detection/core.py, doctr/models/detection/differentiable_binarization.py, doctr/models/detection/linknet.py, references/detection/train.py
This PR adjusts detection postprocessing to img size: If input is smaller than 1000 x 1000, don't perform opening (erosion + dilatation of boxes) because boxes can be too small. The others parameters don't depend on the size of the input (we could reduce min_size_box but this doesn't make sense because a box smaller than 2 pixels would be impossible to read, no matter the size of the input image).
=> fix: adjust detection postprocessing parameters to img size

docs/source/datasets.rst, docs/source/models.rst
This PR adds:
- tab of supported vocabs in doc (dataset)
- vocab to use for each model (models)
closes #235
=> docs: add vocabs in doc

docs/source/index.rst
This PR makes the landing page of the documentation more user-friendly, describing features and models/datasets provided in the package.
Before:
Now:
closes #236
=> docs: improved landing page of documentation

demo/app.py, doctr/documents/reader.py, scripts/analyze.py, test/test_documents_reader.py
Before this PR, the image resolution was computed by default this way in `read_pdf`:
Find pdf dimension, scale by 72 DPI to obtain image dimension.
This raises 2 issues:
- Different document sizes yield to different resolutions (constant DPI)
- For A4 sizes (a huge amount of docs), this method was re-scaling to 840 x 595 pixels which is way to low for very dense docs.
Now we have a constant resolution of 1024 x 1024 by default.
closes #232
=> feat: set default image resolution to 1024 in read_pdf

references/recognition/train.py
This PR fixes a double tensor scaling happening in the recognition script
=> fix: Fixed tensor scaling in recognition script

.github/workflows/main.yml, Dockerfile-api, README.md, api/app/config.py, api/app/main.py, api/app/routes/recognition.py, api/app/schemas.py, api/requirements-dev.txt, api/requirements.txt, api/tests/conftest.py, api/tests/routes/test_recognition.py, docker-compose.yml
Following up on #233, this PR introduces the following modifications:
- adds a minimal FastAPI-based implementation of a text recognition route
- added Docker orchestration
- added API unittests
- added CI job to ensure it runs correctly & that corresponding unittests are run correctly
Here is how the API documentation renders:
I made a test on my own with the following image:
Once the API is running locally on port 8050, with this piece of code:
```
import requests
import io
with open('/home/fg/Downloads/invite.jpeg', 'rb') as f:
data = f.read()
response = requests.post("http://localhost:8050/recognition", files={'file': io.BytesIO(data)})
```
I get the following result
```
In [10]: response.json()
Out[10]: {'value': 'invite'}
```
=> feat: Added minimal API template for text recognition

api/app/main.py, api/app/routes/detection.py, api/app/schemas.py, api/tests/conftest.py, api/tests/routes/test_detection.py
As per #233, this PR introduces the following modifications:
- added text detection route to the API template
- added corresponding API unittests
For the following image:
with this piece of code:
```
import requests
import io
with open('/home/fg/Downloads/detection_sample.jpg', 'rb') as f:
data = f.read()
response = requests.post("http://localhost:8050/detection", files={'file': io.BytesIO(data)})
```
which yields
```
In [4]: response.json()
Out[4]: 
[{'box': [0.826171875, 0.185546875, 0.90234375, 0.201171875]},
{'box': [0.75390625, 0.185546875, 0.8173828125, 0.201171875]}]
```
(IoU > 85% with the GT)
=> feat: Added text detection route to API template

docs/source/models.rst
As per #5, this PR adds instructions for SavedModel saving / loading.
=> docs: Added SavedModel export instructions in doc

Dockerfile-api, api/app/main.py, api/app/routes/detection.py, api/app/routes/ocr.py, api/app/routes/recognition.py, api/app/schemas.py, api/app/vision.py, api/tests/routes/test_ocr.py, doctr/models/core.py
As per #233, this PR introduces the following modifications:
- added an end-to-end OCR route to the API template
- added corresponding API unittests
- optimized API dockerfile
- refactored recognition & detection route model instantiation
- fixed typing inconsistency in page shape export
For the following image:
with this piece of code:
```python
import requests
import io
with open('/home/fg/Downloads/detection_sample.jpg', 'rb') as f:
data = f.read()
response = requests.post("http://localhost:8050/ocr", files={'file': io.BytesIO(data)})
```
which yields
```python
In [4]: response.json()
Out[4]: 
[{'box': [0.75390625, 0.185546875, 0.8173828125, 0.201171875],
'value': 'Hello'},
{'box': [0.826171875, 0.185546875, 0.90234375, 0.201171875],
'value': 'world!'}]
```
(IoU > 85% with the GT) …
=> feat: Added OCR route to API template

doctr/transforms/modules.py, references/detection/train.py, references/recognition/train.py
- added option to plot samples for training sanity check
- refactored transformations
- updated probability of color inversion in training scripts
Here is how it renders for text detection:
and for text recognition:
=> feat: Added sample display option in training script

doctr/models/detection/core.py, doctr/models/detection/differentiable_binarization.py, doctr/models/detection/linknet.py, doctr/models/recognition/core.py, doctr/models/recognition/crnn.py, doctr/models/recognition/sar.py, references/detection/train.py, references/recognition/train.py, test/test_models_detection.py, test/test_models_recognition.py
- fully moved post_processor inside model definition (the predictor has no knowledge of it)
- removed final activation layers from detection models for loss computation
- model output is now a dictionary for all models : if a target is passed, the loss will be computed and returned in the dict. If it isn't, boxes are returned for detection models and preds for recognition models. Additional call options (return_model_outputs, return_preds, return_boxes) can enforce adding extra information in the returned dict. This way, the training mode is completely decorrelated to the model output.
```python
det_model = db_resnet50()
print(det_model(input_t).keys())
print(det_model(input_t, return_model_output=True).keys())
print(det_model(input_t, …
```
=> refactor: Refactored model calls and fixed validation loop

demo/app.py, scripts/analyze.py, scripts/evaluate.py
- fixed demo app with the recent changes in model call method
- enforced training=False in evaluation and analysis scripts
=> fix: Fixed demo app

doctr/models/artefacts/__init__.py, doctr/models/artefacts/face.py, test/test_artefacts.py
This PR adds a new sub_module dedicated to artefacts, and implements a FaceDetector to detect profile pictures on resumes, IDS, driving licenses, passports, ...
Implemented with cv2 Cascade Classifier, which very light & fast.
Samples are displayed below.
=> feat: add FaceDetector in models.artefact

doctr/transforms/modules.py, references/recognition/train.py, test/test_transforms.py
- switched Resize transforms to preserving aspect ratio in recognition training script
- moved `ColorInversion` before Resize to avoid getting a padding with value != 0
- fixed padding offset when preserving aspect ratio
- extended unittests
The following snippet:
```shell
python references/recognition/train.py /home/fg/Downloads/reco_samples sar_vgg16_bn -b 16 --show-samples
```
used to yield:
by switching to aspect ratio preserving Resize:
and now yields (by fixing the resize):
=> fix: Fixed Resize transformation when preserving aspect ratio

doctr/utils/metrics.py, test/test_utils_metrics.py
Following up on #227, this PR introduces the following modifications:
- fixes edge case of metric update when there are no predictions (previously it would reset IoU total to 0)
- only performs IoU computation & assignment in appropriate cases in the update method
- updates unittests
=> fix: Fixed OCRMetric update when there is no predictions

api/tests/routes/test_detection.py, api/tests/routes/test_ocr.py, docs/source/datasets.rst, docs/source/documents.rst, docs/source/utils.rst, doctr/documents/elements.py, doctr/utils/metrics.py, references/detection/train.py, references/recognition/train.py, requirements.txt, scripts/evaluate.py, setup.py, test/test_utils_metrics.py
- added granularity to string comparison : raw comparison, case-insensitive, unidecode comparison, and comparison of unidecoded lower-case pairs
- added this granularity to RecognitionMetric, which has been renamed to `TextMatch`
- added this granularity in the recall & precision computation of `OCRMetric`
- updated requirements accordingly
- updated unittests accordingly
- reflected changes on evaluation script and training scripts
- fixed documentation of `OCRDataset`
- added documentation of `show` methods of `Page` and `Document`
- added documentation of `summary` methods of metrics
=> refactor: Added granularity to evaluation metrics

demo/app.py, doctr/documents/reader.py, test/test_documents_reader.py
This PR fixes 2 bugs spotted on the demo:
- multi-pages pdf were crashing the app
- pdf reader as images was outputing BGR instead of RGB
=> fix: multi-page demo & RGB for pdf reader

doctr/datasets/cord.py, doctr/datasets/core.py, doctr/datasets/detection.py, doctr/datasets/funsd.py, doctr/datasets/loader.py, doctr/datasets/ocr.py, doctr/datasets/recognition.py, doctr/datasets/sroie.py, doctr/models/artefacts/barcode.py, doctr/models/detection/core.py, doctr/models/detection/zoo.py, doctr/models/recognition/zoo.py, references/detection/train.py, references/recognition/train.py, test/test_datasets.py, test/test_datasets_ocr.py, test/test_datasets_recognition.py, test/test_models_detection.py, test/test_models_export.py, test/test_models_recognition.py
- refactored duplicated dataset methods
- forced fp32 for box targets of `OCRDataset` (previously np.float64)
- removed unused imports
- removed unused variables
- added unittests for `OCRDataset`
=> refactor: Refactored dataset methods and removed unused imports

CONTRIBUTING.md, README.md, api/app/routes/detection.py, api/app/routes/ocr.py, api/app/routes/recognition.py, api/app/vision.py
- fixed default channels in image decoding (previously 0 = grayscale, now 3)
- enforced correct resizing by passing list of TF tensor rather than plan tensor
- updated README and CONTRIBUTING references to the API template
=> fix: Fixed image decoding in API template

api/app/routes/recognition.py, doctr/models/core.py, doctr/models/recognition/core.py, doctr/models/recognition/crnn.py, doctr/models/recognition/sar.py, references/recognition/train.py, scripts/evaluate.py, test/test_models.py, test/test_models_detection.py, test/test_models_recognition.py
- adds computation of the sequence probabilities in text recognition model (CRNN: switch from [greedy decoder](https://www.tensorflow.org/api_docs/python/tf/nn/ctc_greedy_decoder) to [beam search decoder](https://www.tensorflow.org/api_docs/python/tf/nn/ctc_beam_search_decoder) / SAR: took the minimum character probability in the sequence)
- reflected changes on API, training and evaluation scripts
- removed `ignore_case` and `ignore_accents` from recognition postprocessors as those operations can be conducted by the user on its own after the export.
=> feat: Added recognition sequence probability

docs/source/index.rst
- added README illustration in the documentation
- reordered sections
- changed model zoo listing to display only the name of the model (rather than adding the full name of the paper)
Here is how it renders:
=> docs: Improved landing page of the documentation

references/detection/train.py
This PR adds 'import wandb' in references/detection/train.py
=> fix: Missing import of wandb in detection training script

doctr/datasets/cord.py, doctr/datasets/ocr.py
To help with the modifications in #281, this PR introduces the following modifications:
- prevents unnecessary computation in the dataset constructor of `CORD`
- cleans up the `OCRDataset` constructor
=> refactor: Avoids unnecessary computation in datasets constructors

doctr/utils/metrics.py, test/test_utils_metrics.py
- added vectorized function to compute IoU between masks
- added function to convert boxes to masks (some extra vectorization is needed to make this optimal)
=> feat: Added IoU computation for masks

references/detection/train.py, references/recognition/train.py
This PR moves the train set loader after the test-only check to avoid a 1-min wait when there is no need to load the full train set.
=> feat: improve loading time when test only

doctr/models/detection/linknet.py
This PR adds an edge_mask in linknet compute_target and compute_loss to enhance spatial resolution of boxes. 
It will add more weight to the edges of boxes, and thus help the model to easily separate words.
=> feat: add edge mask in linknet compute_target

api/app/routes/detection.py, doctr/models/_utils.py, doctr/models/core.py, doctr/models/detection/core.py, doctr/models/detection/differentiable_binarization.py, doctr/models/detection/linknet.py, test/test_models.py, test/test_models_detection.py
This PR introduces 2 fonctions in models._utils.py:
`rotate_page` and `get_bitmap_angle`
These 2 fonctions are used to find the bitmap orientation after segmentation task (in detection postprocessor), and to rotate back the segmentation map to fit straight Bboxes. Angles are passed in the OCRPredictor to similarly rotate the source page, to extract straight crops for the recognition task.
The only remaining part is to add a function to obtain to the (rotated) boxes coordinates in the original image, to return to the user the "original" boxes and to be able to draw polygons on the original (rotated) image.
=> feat: add support for page rotation

test/test_transforms.py
This PR fixes the edge case on the unittest of ColorInversion
=> test: Fixed ColorInversion unittest

doctr/datasets/cord.py, doctr/datasets/detection.py, doctr/datasets/funsd.py, doctr/datasets/ocr.py, doctr/datasets/recognition.py, doctr/datasets/sroie.py
- added bounding box clipping to fix negative coordinates on CORD dataset
- fixed dataset docstrings
- refactored dataset constructors
=> fix: Fixed CORD dataset and refactored dataset constructors

doctr/models/_utils.py, doctr/models/core.py, test/test_models.py
This PR adds a rotate_boxes function to rotate predicted straight bounding boxes when the original document is rotated.
This function is called in the OCRPredictor to compute boxes corresponding to the original document, although we forwarded the model with a rectified (straight) version of the document.
This is an example of a rotated bitmap (black and white), with predicted straight bounding boxes in cyan and rectified bounding boxes (OCR predictions) in yellow:
=> feat: add rotate_boxes in model._utils

README.md, docs/source/index.rst, doctr/models/recognition/__init__.py, doctr/models/recognition/master.py, doctr/models/recognition/transformer.py, test/test_models_recognition.py
This PR implements the [MASTER model](https://arxiv.org/pdf/1910.02562.pdf), following the official [TF implementation](https://github.com/jiangxiluning/MASTER-TF).
This model (based on a transformer decoder, and a resnet/Global Context block encoder) achieved very impressive performances compared to SAR and others, at ICDAR 2021.
The decoder used is exactly the one presented in "Attention is all you need", therefore it is implemented in a recognition.transformer.py. The MASTER is implemented in recognition.master.py.
Closes #215
=> feat: add MASTER in models.recognition module

.github/workflows/doc-deploy.yaml, .github/workflows/main.yml, .github/workflows/os-builds.yml, Dockerfile, Dockerfile-api, README.md, docs/source/installing.rst, doctr/__init__.py, doctr/file_utils.py, requirements.txt, setup.py, test/test_core.py
Following up on #305, this PR introduces the following modifications:
- added a dynamic framework selection module (which can then be used to dynamically import the correct modules in `__init__.py`)
- updated all installation instructions
- updated installation commands
- added a unittest
=> feat: Added a dual framework availability checker

doctr/models/detection/linknet.py, test/test_models_detection.py
This PR adds a compute_focal_loss method in Linknet, the old compute_loss method  is now compute_bce_loss. The focal loss is enabled by default, but the two are available with a focal_loss flag in the call.
=> feat: add focal loss in linknet model

doctr/models/detection/linknet.py
This PR sets the focal loss parameters to alpha = .5 and gamma = 2. in the Linknet.
=> feat: Updated focal loss parameters

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/linknet/__init__.py, doctr/models/detection/linknet/pytorch.py, doctr/models/detection/linknet/tensorflow.py, doctr/models/detection/zoo.py, doctr/models/preprocessor/tensorflow.py, test/pytorch/test_models_detection.py
- added PyTorch support of LinkNet architectures
- renamed `out_chan` to `num_classes` for the number of output classes in detection models
- refactored preprocessor call in tensorflow
=> feat: Added support of LinkNet in PyTorch

doctr/transforms/functional/__init__.py, doctr/transforms/functional/pytorch.py, doctr/transforms/functional/tensorflow.py, doctr/transforms/modules/__init__.py, doctr/transforms/modules/base.py, doctr/transforms/modules/tensorflow.py, test/pytorch/test_transforms.py
- added ColorInversion support in PyTorch
- refactored transforms dispatch
- fixed typing of `doctr.transforms.functional.invert_colors`
_Note: RandomJPEGQuality doesn't have a pytorch equivalent, but there is plenty of other similar stuff & AutoAugment_
=> feat: Added support of remaining transforms in PyTorch

doctr/models/__init__.py, doctr/models/utils/__init__.py, doctr/models/utils/pytorch.py, doctr/models/utils/tensorflow.py, test/pytorch/test_models_utils.py
- added PyTorch support of `load_pretrained_params` and `conv_sequence`
- fixed models `__init__`
- added unittests for pytorch support
_Note: IntermediateLayerGetter is already natively supported in PyTorch_
=> feat: Added PyTorch support to models.utils

doctr/models/backbones/resnet/__init__.py, doctr/models/backbones/resnet/pytorch.py, doctr/models/backbones/resnet/tensorflow.py, doctr/models/backbones/vgg/__init__.py, doctr/models/backbones/vgg/tensorflow.py, doctr/models/utils/pytorch.py, test/pytorch/test_models_backbones.py, test/pytorch/test_models_utils.py
- added support of `resnet31` as Pytorch backbone
- renamed base `Resnet` class to `ResNet`
- renamed `conv_sequence` Pytorch version to `conv_sequence_pt`
=> feat: Added PyTorch support of ResNet-31

doctr/models/backbones/vgg/__init__.py, doctr/models/backbones/vgg/pytorch.py, test/pytorch/test_models_backbones.py
- added pytorch version of `vgg16_bn`
=> feat: Added PyTorch support of VGG backbones

doctr/datasets/cord.py, doctr/datasets/funsd.py, doctr/models/backbones/vgg/pytorch.py, doctr/models/detection/linknet/base.py, doctr/models/preprocessor/pytorch.py, doctr/models/recognition/core.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/transformer/pytorch.py, doctr/transforms/modules/tensorflow.py
- silenced numpy & pytorch dtype warnings
- removed unused imports and variables
- fixed MASTER forward tensor concatenation
- fixed typing annotations in MASTER & transformer
=> refactor: Cleaned import and typing annotations

doctr/datasets/utils.py, doctr/models/recognition/core.py, doctr/models/recognition/master/base.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py, doctr/models/recognition/transformer/pytorch.py, doctr/models/recognition/transformer/tensorflow.py, test/pytorch/test_models_recognition.py, test/test_datasets_utils.py
MASTER model was not trained properly due to a misalignment in the loss function, this is now fixed. More precisely:
- Loss function is updated (right shift for gt sequences)
- `encode_sequences` is  improved to support not only `EOS` but also `SOS` and `PAD` symbols, which are mandatory to train MASTER (`SOS` to shift gt to the right, and `PAD` because we need to mask where `PAD` in the loss but nos `EOS`). It is important to note that default behavior of this function is NOT modified, when pad and sos arguments are left to `None`, the function still pad with `EOS` at the end of each sequence. When `PAD` is provided, sequences are concatenated with `EOS` before adding `PAD` to fill the matrix.
- Updated corresponding unitests.
- When gt are given in the call, but `training=False`, the …
=> fix: bug in MASTER loss

.github/ISSUE_TEMPLATE/bug_report.md, scripts/collect_env.py
This PR extends the scope of environment collection to PyTorch and Torchvision and updates the issue template accordingly.
Running
```shell
python scripts/collect_env.py
```
yields something similar to :
```shell
Collecting environment information...
DocTR version: 0.3.0a0
TensorFlow version: 2.5.0
PyTorch version: 1.8.0 (torchvision: 0.9.0)
OpenCV version: 4.5.1
OS: Ubuntu 20.04.2 LTS
Python version: 3.8
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): No
CUDA runtime version: 11.2.152
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0 …
```
=> feat: Added PyTorch & torchvision to environment collection

doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py
This PR adds the bottleneck ratio of 1/16 in both tf & pt MASTER models, and set the number of multi aspect context to 8 as described in paper. 
=> feat: add bottleneck ratio in MASTER

doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py, doctr/models/recognition/transformer/pytorch.py, doctr/models/recognition/transformer/tensorflow.py
This PR adds dropout in both tf & pytorch MASTER models
=> feat: add dropout in MASTER

.github/workflows/scripts.yml
This PR fixes the trigger of the CI job to run the scripts (wasn't triggering previously)
=> chore: Fixed trigger of script testing job

doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py
This PR simply renames the `feature_extractor` attribute to `feat_extractor` to keep the same naming conventions across models.
=> refactor: Renamed MASTER feature extractor attribute

doctr/transforms/modules/pytorch.py, test/pytorch/test_transforms_pt.py
In rare cases, when the original image has the same aspect ratio as the target size, the resize was not performed correctly. This PR fixes that and adds a test case in corresponding pytorch unittests.
=> fix: Fixed Resize transfo in PyTorch when aspect ratio matches the target

doctr/datasets/detection.py, doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/linknet/base.py, test/tensorflow/test_models_detection_tf.py
- added box coord clipping to avoid rounding errors in detection datasets
- added target validation for detection models to avoid silent failures
- added unittests for target validation
=> feat: Added box coord clipping and target validation for detection tasks

doctr/models/_utils.py, doctr/models/core.py, doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/linknet/base.py, doctr/transforms/functional/pytorch.py, doctr/transforms/functional/tensorflow.py, doctr/utils/geometry.py, requirements.txt, setup.py, test/common/test_models.py, test/common/test_utils_geometry.py, test/pytorch/test_transforms_pt.py, test/tensorflow/test_transforms_tf.py
This PR adds a rotate functional transformation in both pt and tf transforms modules.
The function `rotate_boxes` is moved to `utils/geometry.py`, since it is no longer useful only for models (otherwise we need to deal with circular imports).
Updated unitests as well.
linked to #352
=> feat: add rotate in transforms

references/detection/train_tensorflow.py, references/recognition/train_tensorflow.py
This PR adds a CosineDecay lr scheduler in both tensorflow training scripts.
=> feat: add learning rate scheduler in TF training scripts

doctr/models/backbones/resnet/tensorflow.py, doctr/models/backbones/vgg/tensorflow.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/crnn/tensorflow.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/sar/tensorflow.py, doctr/models/recognition/transformer/pytorch.py, doctr/models/recognition/zoo.py, test/conftest.py, test/pytorch/test_models_detection_pt.py, test/pytorch/test_models_recognition_pt.py, test/tensorflow/test_models_backbones_tf.py, test/tensorflow/test_models_recognition_tf.py
- fixed MASTER input_shape (causes failure for predictor)
- fixed multiple buffer registration (otherwise changing device doesn't propagate to this tensor)
- fixed LSTM dimensioning in CRNN (needed to be dynamic with backbone output shape)
- added `crnn_resnet31` which was missing from PyTorch support
- removed `include_top` constructor argument from backbones
- fixed compatibility with GPU input
- re-enabled GPU for unittests (when CUDA available)
- added missing tests for recognition zoo
=> fix: Fixed recognition model PyTorch versions and added GPU compatibility

doctr/datasets/datasets/pytorch.py, references/detection/train_pytorch.py, references/recognition/train_pytorch.py, requirements-pt.txt, setup.py
Following up on #190, this PR introduces the following modifications:
- added automatic workers number selection for PyTorch trainings
- switched image reading backend from torchvision to PIL + tensor conversion
- reflected changes on training scripts
- had to update PIL requirements due to https://github.com/python-pillow/Pillow/issues/5571
Iterating with the dataloader on FUNSD gets a 25%+ speedup with the same number of workers (3X compared to the original default number of workers)
Closes #190
=> feat: Optimized data loading for PyTorch

doctr/datasets/cord.py, doctr/datasets/datasets/base.py, doctr/datasets/datasets/pytorch.py, doctr/datasets/datasets/tensorflow.py, doctr/datasets/detection.py, doctr/datasets/funsd.py, doctr/datasets/ocr.py, doctr/datasets/recognition.py, doctr/datasets/sroie.py, references/detection/train_tensorflow.py, references/recognition/train_tensorflow.py, test/pytorch/test_datasets_pt.py, test/tensorflow/test_datasets_tf.py
Following up on #263, this PR introduces the following modifications:
- switched default image dtype of TF datasets to FP32 (before it was `tf.uint8`)
- added FP16 mode on all datasets
- updated references script to reflect changes (no need to perform 255 division manually anymore)
Please note that there is a breaking change here, the default image dtype of datasets in TF has been switched from `tf.uint8` (between 0 and 255) to `tf.float32` (between 0 and 1).
=> feat: Added FP16 support to doctr.datasets

demo/app.py, scripts/analyze.py
This PR removes the resizing step of PDF image rendering to square images. The reason behind that is that while it's indeed optimized if the predictor target size is that specific size if there are multiple preprocessors inside, it yields double interpolation.
=> fix: Removed PDF forced square resize from demo & analysis script

doctr/transforms/functional/pytorch.py, doctr/transforms/functional/tensorflow.py, test/pytorch/test_transforms_pt.py, test/tensorflow/test_transforms_tf.py
This PR adds a `crop_detection` function in both tf & pt `transforms.functional`. This function crops a tf or pt image according a given crop_box, and crops as well the given array of bboxes (relative or absolutes).
=> feat: add crop functional transformation

README.md, demo/app.py
- added tip to enlarge images
- switched to 4 columns display
- added page selection (for multi-page PDF)
- speeded up analysis by only analyzing the selected page
- added JSON output display (foldable, and can be copied to clipboard)
- updated demo display in README
Here is how it renders:
Closes #234
=> feat: Added page selection & JSON display to demo

doctr/datasets/datasets/tensorflow.py
This PR fixes a bug introduced in #367:
- `tf.image.convert_image_dtype` already performs the 255 division when it receives a float dtype.
- the extra 255 division was wrongly placed afterward and is removed in this PR
=> fix: Removed extra 255 division

doctr/datasets/recognition.py, test/pytorch/test_datasets_pt.py, test/tensorflow/test_datasets_tf.py
This PR allows recognition datasets to be merged.
=> fix: Recognition dataset merging

doctr/transforms/functional/pytorch.py, doctr/transforms/functional/tensorflow.py
This PR fixes the rotation in the transform module.
(When `min_angle` > 0, if the angle was less than `min_angle` boxes were not rotated and returned in a straight way (4 coords), now boxes are always composed of 5 coords, even if the angle is 0.)
=> fix: transform test bug in CI

doctr/models/recognition/master/pytorch.py, doctr/models/recognition/sar/pytorch.py
This PR fixes both SAR & MASTER loss in pytorch which were composed of more than 1 scalar, which was triggering an error when training:
`RuntimeError: grad can be implicitly created only for scalar outputs`
=> fix: Torch loss dimension

references/recognition/train_pytorch.py, references/recognition/train_tensorflow.py
This PR adds the option to train recognition with multiple datasets.
the arg `data_path` in the script is replaced by a `train_data_path`, a list of 1 or more paths and `val_data_path`, a path.
The structure inside each path must be: `path/images/` and `path/labels.json`.
=> feat: reco training script with multi paths sets

references/recognition/train_tensorflow.py
This PR removes a deprecated arg in the training script.
=> fix: Removed deprecated arg in training script

references/detection/train_pytorch.py, references/recognition/train_pytorch.py
Following up on #347, this PR adds LR scheduler to the PyTorch training scripts.
Closes #347
=> feat: Added schedulers to Pytorch training scripts

doctr/datasets/utils.py, test/common/test_datasets_utils.py
- renamed `encode_sequence` into `encode_string`
- improved speed of all encoding but leveraging `map`
- fixed sequence size resolution (missing EOS count)
- added option to have a soft target_size (taking the minimum between specified size and dynamic seq length)
- updates unittests accordingly
Resolves #387
=> feat: Added dynamic sequence encoding

doctr/models/backbones/mobilenet/tensorflow.py, doctr/models/detection/differentiable_binarization/tensorflow.py, doctr/models/utils/tensorflow.py, test/tensorflow/test_models_backbones_tf.py
- fixed the implementation of mobilenetV3 versions
- passes the input shape for a proper model build in the unittests of backbones
=> fix: Fixed framework alignment on MobileNet V3 implementations

docs/source/datasets.rst, doctr/datasets/__init__.py, doctr/datasets/classification/__init__.py, doctr/datasets/classification/base.py, doctr/datasets/classification/pytorch.py, doctr/datasets/classification/tensorflow.py, doctr/datasets/loader.py, doctr/io/image/pytorch.py, doctr/io/image/tensorflow.py, test/pytorch/test_datasets_pt.py, test/pytorch/test_io_image_pt.py, test/tensorflow/test_datasets_tf.py, test/tensorflow/test_io_image_tf.py
Following up on #262, this PR introduces the following modifications:
- extends tensor conversion functions
- added a character generation dataset (upcoming potential update with #408 @charlesmindee)
- updates unittests accordingly
=> feat: Added character generator dataset

doctr/models/backbones/mobilenet/__init__.py, doctr/models/backbones/mobilenet/pytorch.py, test/pytorch/test_models_backbones_pt.py
Following up on #255, this PR introduces the following modifications:
- adds pretrained params for PyTorch mobilenets (character classification)
```python
import torch
from doctr.models import mobilenet_v3_small
from doctr.datasets import VOCABS
from doctr.datasets.classification.base import synthesize_char_img
from doctr.io import tensor_from_pil
from torchvision.transforms import Normalize
model = mobilenet_v3_small(pretrained=True).eval()
img = synthesize_char_img('a', font_family='FreeMono.ttf')
transfo = Normalize(mean=(0.694, 0.695, 0.693), std=(0.299, 0.296, 0.301))
with torch.no_grad():
out = model(transfo(tensor_from_pil(img)))
print(VOCABS['french'][out.argmax().item()])
```
yields:
```
'a'
```
=> feat: Added pretrained PyTorch mobilenets

doctr/models/backbones/mobilenet/pytorch.py
This PR simply fixes the input shape for the pretrained Mobilenet V3-Large in PyTorch
=> fix: Fixed config for mobilenet_v3_large in PyTorch

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/linknet/pytorch.py, doctr/models/recognition/crnn/pytorch.py
Following up on #422, this PR switches back to the common parameter loading mechanism. 
Previously, some pytorch models' factory functions were throwing errors when `pretrained=True`. With this PR, it throws a warning and proceeds with param initialization when no checkpoint is available.
=> fix: Fixed PyTorch param loading

references/detection/train_pytorch.py, references/recognition/train_pytorch.py
- added GPU selection by default if available in PyTorch scripts
- added console warning when running on CPU
- fixed missing GPU support on text recognition training (considerable speedup)
Resolves #409
=> fix: Fixed GPU selection in PyTorch training scripts

doctr/models/backbones/resnet/__init__.py, doctr/models/backbones/vgg/__init__.py, doctr/models/recognition/sar/__init__.py
Fixed error while importing functions like `is_tf_available` and `is_torch_available` because it is in `file_utils.py` file.
=> refactor: Specified imports of file_utils in __init__.py

doctr/__init__.py
This PR fixes a conditional import of the submodule `doctr.datasets` that was wrongly exclusive to Tensorflow.
=> chore: Fixed dataset submodule import

.github/workflows/demo.yml, .github/workflows/scripts.yml, scripts/evaluate.py
Following up on #429, this PR introduces the following modifications:
- adds a job to run the `evaluate.py` script on FUNSD
- adds a job to check the `collect_env.py` script
- adds a job to check whether we can run the demo
- adds an option to run the evaluation script on the first N samples (the CI job checks it for the 10 first samples)
=> chore: Added CI jobs to check evaluate, collect_env & demo

.github/workflows/demo.yml, .github/workflows/references.yml, references/classification/train_pytorch.py, references/classification/train_tensorflow.py
As per #429, this PR introduces the following modifications:
- added option to change the font family in the character classification script
- added also an option to change the number of samples during training & validation
- added CI jobs to run the classification training for a small epoch
- increased the sleep in CI job before checking if the demo is up
=> chore: Added CI jobs to check classification training

.github/workflows/scripts.yml, doctr/models/_utils.py, doctr/models/core.py, scripts/analyze.py, scripts/evaluate.py
As per #428, this PR introduces the following modifications:
- added option to correctly crop images that are channels_first
- updated predictors accordingly
- added support of PyTorch in the evaluation script
- added support of PyTorch in the analysis script
- added CI job to check Pytorch evaluation
- added metric formatter when a metric is undefined
- fixed predictor call when some crops have a size of 0
Resolves #428
=> fix: Fixed PyTorch tensor cropping and extended script support

doctr/models/core.py
This PR fixes the cropping mode when both frameworks are available. #458 introduced an issue occurring for users with both frameworks installed. SInce the priority (default framework mode) is TensorFlow, this PR switches the condition to ensure proper cropping.
=> fix: Fixed cropping mode in predictor

requirements-pt.txt, requirements.txt, setup.py
This PR fixes a vulnerability spotted in https://github.com/advisories/GHSA-98vv-pw6r-q6q4 regarding previous versions of Pillow, by constraining the allowed versions of Pillow to recent releases.
=> chore: Updated Pillow version constraints to avoid vulnerability

README.md
This PR fixes a broken URL that was referring to the former `documents` module which has been renamed to `io`.
=> docs: Fixed broken URL in README

doctr/datasets/vocabs.py
PR for portuguese entry in Vocab.
=> feat: Added portuguese entry in VOCAB

docs/source/datasets.rst, doctr/datasets/vocabs.py, doctr/models/backbones/mobilenet/pytorch.py, doctr/models/backbones/mobilenet/tensorflow.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/crnn/tensorflow.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/sar/tensorflow.py
- fixed the french vocab (to avoid breaking change, the `french` vocab was remapped to `legacy_french`)
- added multiple european vocabs in a more flexible way (english, spanish, german)
- updated documentation accordingly
_Note: the `legacy_french` vocab will be deprecated as soon as all models have been retrained with the correct `french` vocab_
=> refactor: Refactored VOCABs

demo/app.py, docs/source/models.rst, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/crnn/tensorflow.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/sar/tensorflow.py, doctr/models/recognition/zoo.py, test/pytorch/test_models_recognition_pt.py, test/tensorflow/test_models_recognition_tf.py, test/tensorflow/test_models_tf.py
- deprecated `crnn_resnet31` and `sar_vgg16_bn` and they use combinations of backbones that aren't recommended by their respective paper and do not bring about perf or speed boost.
- updated documentation accordingly
- updated unittests accordingly
- updated demo reco model selection
=> refactor: Deprecated crnn_resnet31 and sar_vgg16_bn

.github/workflows/demo.yml, .github/workflows/scripts.yml
Unfortunately, the CI is getting slower by the way and the suspect is mostly macOS jobs. This PR keeps macOS jobs to build the project and collect environment but removes the rest to speed up PR CI jobs.
=> chore: Removed some CI jobs with macOS

README.md, docs/source/utils.rst, doctr/datasets/classification/base.py, doctr/io/elements.py, doctr/models/recognition/__init__.py, doctr/utils/fonts.py, doctr/utils/visualization.py, test/common/test_io_elements.py, test/common/test_utils_fonts.py, test/common/test_utils_visualization.py
- refactored all font selection code into a `doctr.utils.fonts` module (for character generation & page synthesis)
- fixed typo `synthetize_page` --> `synthesize_page`
- improve page synthesis thanks to the new font module
- added a `synthesize` method to `Document` and `Page`
- added synthesis visualization sample in the README
As shown in the README, here is how it renders:
=> feat: Improved font resolution and page synthesis

doctr/transforms/modules/base.py
In very rare cases, the generated coordinates of the crop from `RandomCrop` were out of bounds (negative usually). This PR ensures that proper rounding is used and adds clipping to avoid issues.
=> fix: Prevents rounding errors in RandomCrop

doctr/models/backbones/mobilenet/pytorch.py, doctr/models/backbones/mobilenet/tensorflow.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/crnn/tensorflow.py
- adds MobileNet V3 counterparts with 3 rectangular strides
- replaces mobilenet backbones in CRNN
I checked locally and the training now yields 92%+ of exact match after a single epoch (vs. 20% before)
=> feat: Added rectangular stride MobileNets

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/recognition/crnn/pytorch.py
This PR adds pytorch ckpts for crnn_vgg_16_bn and mobilenet_v3_large, here is the benchmark performed with the ckpts:
```
FUNSD
Text Detection - Recall: 80.98%, Precision: 85.28%, Mean IoU: 68.91%
Text Recognition - Accuracy: 85.85% (unicase: 86.76%)
OCR - Recall: 67.90% (unicase: 68.52%), Precision: 71.51% (unicase: 72.17%), Mean IoU: 68.91%
CORD
Text Detection - Recall: 80.48%, Precision: 66.62%, Mean IoU: 56.98%
Text Recognition - Accuracy: 92.53% (unicase: 92.92%)
OCR - Recall: 70.80% (unicase: 71.12%), Precision: 58.60% (unicase: 58.86%), Mean IoU: 56.98%
RECEIPTS
Text Detection - Recall: 84.70%, Precision: 85.62%, Mean IoU: 72.19%
Text Recognition - Accuracy: 91.70% (unicase: 92.45%)
OCR - Recall: 76.87% (unicase: 77.51%), Precision: 77.70% (unicase: 78.34%), Mean IoU: 72.19%
IDS …
```
=> feat: add pytorch ckpts for crnn & mobilenet_v3_large

demo/app.py, demo/requirements.txt
Hello!
I built a Space demo hosting your Streamlit example (link at https://huggingface.co/spaces/osanseviero/doctr). It works great and is much faster than I expected.
I did face some issues during the development. I hope this PR fixes them:
1. You suggest to install `doctr` in the `requirements` but I think that's actually an unrelated package, it should be `python-doctr`.
2. But then `out.pages[0].synthesize()` threw an error saying `Page` class has no `synthesize` method. This was introduced in #472 so I don't think it's in the recent release. 
Given 1 and 2, and that #472 will probably be soon in a release, maybe we could change `requirements.txt` to install `python-doctr[tf]` instead of installing directly from GitHub. WDYT?
=> Misc fixed to Streamlit demo

api/requirements.txt, references/requirements.txt
- fixes the requirements of the API (in case the user installs the demo reqs without Docker, it was fetching the pypi index named "doctr" which is a different project). Using a git branch installation would have required to modify the Dockerfile to add git.
- fixes the training script requirements (since this will most often not be done in a docker container, we can assume the user has git, hence the git branch installation)
cc @jonathanMindee
=> chore: Fixed requirements for the API template & training scripts

doctr/utils/visualization.py
This PR fixes the page synthesis feature. Up until now, we have relied on the support of text drawing using Pillow. However as pointed out by #495, this support is limited. 
This snippet crashes:
```python
from PIL import Image, ImageDraw
img = Image.new('RGB', (100, 100), color=(255, 255, 255))
d = ImageDraw.Draw(img)
d.text((0, 0), '€', fill=(0, 0, 0))
```
this PR changes this by catching the `UnicodeEncodeError` and normalizing the string as follows:
```python
from PIL import Image, ImageDraw
from unidecode import unidecode
img = Image.new('RGB', (100, 100), color=(255, 255, 255))
d = ImageDraw.Draw(img)
d.text((0, 0), unidecode('€'), fill=(0, 0, 0))  #  <--- over HERE
```
Please note that in doing so, some string will be synthesized with different length cf the snippet below:
```
In …
```
=> fix: Fixed support of characters out of latin-1 in page synthesis

doctr/models/builder.py, doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, test/common/test_models_builder.py
So I noticed that when the predictor wasn't detecting anything, the number of pages in the export wasn't matching the input. Even if it doesn't manage to detect anything, the export should reflect the correct number of pages.
- refactors the `DocumentBuilder` to ensure that localization predictions are the same length as the text predictions, as well as the number of pages
- fixed zero-sized crop filtering (on multi-pages cases)
- refactored crop preparation & prediction processing for all framework-specific predictors
Using this image
with the following snippet:
```python
from doctr.models import ocr_predictor
from doctr.io import DocumentFile
predictor = ocr_predictor(pretrained=True)
doc = …
```
=> fix: Fixed inconsistency of export when nothing is detected

.github/workflows/main.yml
For clarity and CI speedups, this PR splits the unittests of `common`, `pytorch`, and `tensorflow`.
This brings several advantages:
- many unittests will now be done in parallel instead of making `pytest-tf` slower
- when an error occurs, it's easier to spot right now if it involves any of the framework
=> chore: Split common, torch & tensorflow unittests

.github/workflows/main.yml
This PR fixes the pytest CI job for TensorFlow. The coverage file was wrongly named in #498 and thus this coverage report was not uploaded to codecov.
=> chore: Fixed coverage upload of TF unittests

references/classification/train_pytorch.py, references/classification/train_tensorflow.py, references/recognition/train_pytorch.py, references/recognition/train_tensorflow.py
This PR adds the option to select a different vocab for training (character classification and text recognition).
=> feat: Added option to select vocab for training

.github/workflows/main.yml
Similarly to #503, this PR fixes the pytest CI job for common. The coverage file was wrongly named in #498 and thus this coverage report was not uploaded to codecov.
=> chore: Fixed coverage upload of common

README.md, docs/source/index.rst, docs/source/models.rst, docs/source/using_model_export.rst, docs/source/using_models.rst, doctr/models/detection/zoo.py, doctr/models/recognition/master/tensorflow.py, doctr/models/recognition/zoo.py, doctr/models/zoo.py
- removes the mention that PyTorch is in beta in the README
- in the documentation, split benchmark & export model from actual docstrings: "Using DocTR" section doesn't include any function/class documentation but explains how some features work and provides benchmarks. Hyperlinks were added so that users can easily access the signature.
Here is the new navigation menu:
Please note that this doesn't include the PyTorch benchmark for now!
=> docs: Restructured documentation

requirements.txt, setup.py
This PR tries to fix the CI issue that happens since the release of keras 2.7 https://github.com/keras-team/keras/releases/tag/v2.7.0 by constraining the version to a lower index.
cf. https://github.com/tensorflow/tensorflow/issues/52937 & https://github.com/keras-team/keras/issues/15585
=> chore: Fixed keras version constraint

doctr/models/builder.py
This PR removes a console print introduced in #551.
=> refactor: Removed console print in builder

doctr/datasets/classification/base.py, doctr/datasets/detection.py, doctr/io/elements.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/crnn/tensorflow.py, doctr/models/recognition/sar/tensorflow.py, doctr/utils/visualization.py, mypy.ini
- defuses XML attacks
- removed unused imports
=> refactor: Removed unused imports and prevents XML attacks

doctr/io/elements.py, doctr/utils/visualization.py
There was a wrong description in the docstring which results also in the wrong dim order in export_as_xml 
now the parser example runs also correct
=> docs: Fixed docstring and export as xml dim bug

docs/source/datasets.rst, doctr/datasets/__init__.py, doctr/datasets/doc_artefacts.py, test/pytorch/test_datasets_pt.py, test/tensorflow/test_datasets_tf.py
- Implemented class wrapper for artefact detection dataset
=> feat: added DocArtefacts dataset

doctr/models/predictor/tensorflow.py
Previously, if model is a TF version of OCRPredictor, `print(model) `shows only `OCRPredictor() ` which is not too informative. It now prints the architecture of the underlying det_predictor and reco_predictor.
=> feat: :sparkles: add det/reco_predictor arch in OCRPredictor.__repr__

demo/app.py
- adds `db_mobilenet_v3_large` and `crnn_mobilenet_v3_small` as new options for model selection
- updates the column creation to avoid warnings with latest streamlit versions
=> feat: Added new architectures to model selection in demo

README.md, scripts/analyze.py
Slight fixes and modification of the doc:
- fixed typo in readme suggested code using demonstrating synthesize
- Added the mention to tensorflow-addons
- Added model names in front of papers
- Mentionned in help of the noblock option of analyze.py that it's only used for CI.
=> docs: :memo: update readme and help in analyse.py

doctr/datasets/detection.py, doctr/datasets/recognition.py
adding blank line between docstring and constructor (format)
and fix two wrong docstrings / docu
=> docs: Fixed docstrings of datasets

doctr/models/detection/core.py, doctr/utils/geometry.py, references/classification/train_pytorch.py, references/classification/train_tensorflow.py, references/classification/utils.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/detection/utils.py, references/recognition/train_pytorch.py, references/recognition/train_tensorflow.py, references/recognition/utils.py
- added option to run the training in AMP
- updated information logged into W&B
- fixed sample plotting in trainings
- fixed compatibility of DBNet with data type different from fp32
=> feat: Added support of AMP to all PyTorch training scripts

.github/workflows/demo.yml, api/app/routes/detection.py, api/app/routes/ocr.py, api/app/routes/recognition.py
Following up on some QA feedback, this PR introduces the following modifications:
- specifies that all routes support only images and not PDF for now
- cleaned the expected route status
- improved the CI check: it used to check that the base URL is accessible, and now it will check whether it can access the swagger/docs
cc @RBMindee
=> docs: Specified that the API template only supports images for now

doctr/utils/geometry.py
This PR is a quick fix on the rot-training branch to generate correct rotated boxes for rotated images.
=> fix: :bug: quick fix rotation

Makefile
This PR fixes the Makefile as it doesn't work when tabs are converted into spaces.
=> fix: Fixed Makefile by converting spaces to tabs

.flake8, .github/workflows/style.yml, doctr/datasets/datasets/base.py, doctr/utils/metrics.py, tests/tensorflow/test_datasets_loader_tf.py, tests/tensorflow/test_models_zoo_tf.py
- updates flake8 config to spot unused imports, docstring backslack issues, undefined variables
- updated codebase to match those constraints
=> style: Updated flake8 config to spot unused imports & undefined variables

README.md, api/README.md
Following on some QA feedback, this PR adds a dedicated README for the API template. It provides curated examples of inputs and outputs on each route.
=> docs: Added README specific for the API with route examples

doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/sar/tensorflow.py
This PR specifies the reason of the one hot symbol encoding in the SAR decoder following up on #578.
cc @khalidMindee
=> docs: Specified comment in SAR about symbol encoding

README.md, docs/requirements.txt, docs/source/conf.py, docs/source/index.rst, docs/source/notebooks.md, notebooks/README.md, setup.py
- adds a `notebooks` folder that will reference all notebooks to be displayed in the documentation
- added a symlink in sphinx documentation to use this README to generate an identical page in the documentation
- added corresponding sphinx deps to handle tables
Here is how the corresponding documentation page renders:
Closes #558
=> docs: Added links to tutorial notebooks in the documentation

references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/recognition/train_tensorflow.py
- adds missing console log of validation metrics in the detection training
- removes support of Tensorboard
=> fix: Adds missing console log and removed Tensorboard

doctr/datasets/cord.py, doctr/datasets/datasets/base.py, doctr/datasets/datasets/pytorch.py, doctr/datasets/datasets/tensorflow.py, doctr/datasets/detection.py, doctr/datasets/doc_artefacts.py, doctr/datasets/iiit5k.py, doctr/datasets/ocr.py, doctr/datasets/recognition.py, doctr/datasets/sroie.py, doctr/datasets/svt.py, doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/linknet/base.py, doctr/models/preprocessor/pytorch.py, doctr/models/preprocessor/tensorflow.py, tests/pytorch/test_datasets_pt.py, tests/pytorch/test_models_preprocessor_pt.py, tests/tensorflow/test_datasets_tf.py, tests/tensorflow/test_models_preprocessor_tf.py
- removed fp16 support from datasets and models' preprocessors
- removed support of np.float16 for targets in text detection models
- adapted unittests
=> refactor: Drops support of np.float16

references/classification/train_pytorch.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/recognition/train_pytorch.py, references/recognition/train_tensorflow.py
- removes unnecessary metric reset (it's already done at the beginning of `evaluate`)
- added missing support of GPU for character classification in PyTorch
- improved memory pinning for CPU training (if "True" it preallocates the memory on GPU, but in case of CPU training, we don't want that)
=> feat: Added GPU support for classification and improve memory pinning

doctr/datasets/utils.py, doctr/models/recognition/crnn/pytorch.py, tests/common/test_datasets_utils.py
- extends arg type support of `decode_sequence`
- refactored CTC decoding in PyTorch bringing a 10x speedup
=> refactor: :zap: Speeded up CTC decoding in PyTorch by x10

README.md, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/models/zoo.py
This PR adds the 2 flags introduced in #551 in the highest level predictor so the user can easily choose the parameters of the rotation.
=> feat: add 2 new rotation flags in the ocr_predictor

docs/build.sh
- cleans up the remaining files after multi-version build
- fixed a silent fail of `git checkout` because of untracked files (which are now removed once the specific doc version is built)
=> docs: Fixed documentation build

.github/workflows/style.yml, doctr/models/recognition/utils.py, references/classification/train_pytorch.py, references/obj_detection/train_pytorch.py
- fixes typing due to the latest rapidfuzz release
- fixes the import order
- ensures the isort CI check fails when files are modified
=> style: Fixed isort and typing checks

doctr/models/detection/differentiable_binarization/base.py
The threshold target map (of the DB) was set to be an uint8 tensor, but it should contains values between 0 and 1 (which were cast to 0).
This is now fixed.
=> fix: :bug: bug canvas dtype for threshold target

doctr/models/detection/zoo.py, doctr/models/zoo.py
This PR fixes the issue #646.
The detection predictor should receive the assume_straight_boxes flag when instantiated. 
=> fix: :bug: assume_straight_pages in predictor

.github/workflows/style.yml, .isort.cfg, doctr/models/predictor/base.py, references/classification/train_pytorch.py, references/classification/train_tensorflow.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/obj_detection/train_pytorch.py, references/recognition/train_pytorch.py, references/recognition/train_tensorflow.py, setup.cfg
This PR tries to solve why isort doesn't throw an error while there is a file on `main` with the wrong import order. This finally manages to get some isort errors when needed (cf. https://github.com/mindee/doctr/runs/4356017960?check_suite_focus=true)
=> ci: Fixed silent isort failure

doctr/utils/metrics.py, tests/common/test_utils_metrics.py
- adds `rbox_iou` function to compute IoU between sets of rotated bounding boxes
- replace iou computation in task metrics with `rbox_iou` while adding a `use_broadcasting` boolean flag
- adds missing constructor arg description in docstrings
- fixes typos in multiple docstrings
=> feat: Added rbox_iou function with a memory-savy option

Makefile
This PR simply follows up on #655 to update the Makefile for contributors to use isort properly.
cc @felixdittrich92 
=> fix: Updates Makefile to match CI

doctr/utils/metrics.py
This PR simply fixes a typo in the math formula of the metric expression in docstrings.
=> docs: Fixed typo in the docstrings of metrics

doctr/models/detection/differentiable_binarization/base.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py
This PR fixes the rotation arg in training scripts:
- it is now passed in the model to instantiate the postprocessor correctly
- it is not passed in the dataset constructor, otherwise it will load our annotations as rotated boxes, but we have straight boxes and we rotate the images afterwards as a transformation in the get_itm fn.
=> fix: rotation arg in training scripts

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/differentiable_binarization/tensorflow.py
This PR adds `num_classes` as constructor param of DBNet in TF, which was the only text detection model missing this arg.
=> feat: Added missing output classes param in DBNet

doctr/models/detection/_utils/__init__.py, doctr/models/detection/_utils/pytorch.py, doctr/models/detection/_utils/tensorflow.py, tests/pytorch/test_models_detection_pt.py, tests/tensorflow/test_models_detection_tf.py
The use of cv2 for erosion & dilation is limiting for export in ONNX or SavedModel. Following cv2 [documentation](https://opencv24-python-tutorials.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html#opening), this PR introduces the following modifications:
- adds implementation of erosion & dilation in Pytorch & TensorFlow
- adds unittests accordingly
This is the first to improve export compatibility and GPU post-processing for text detection models.
=> feat: Implements erosion & dilation in PyTorch & TF

doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/linknet/base.py, doctr/models/detection/linknet/pytorch.py, doctr/models/detection/linknet/tensorflow.py
- fixed `edge_mask` building
- fixed `seg_target` for PyTorch (was built as channels last)
- removes focal_loss option in LinkNet loss computation
=> fix: Fixed LinkNet target & loss computation

doctr/datasets/cord.py, doctr/datasets/detection.py, doctr/datasets/doc_artefacts.py, doctr/datasets/funsd.py, doctr/datasets/recognition.py, doctr/datasets/sroie.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
- adds the file existence check in `doctr.datasets.DetectionDataset`
- refactors `RecognitionDataset` constructor
- adds unittest for file existence check
=> feat: Added file existence check in DetectionDataset

requirements-pt.txt, requirements.txt, setup.py
This PR allows the PyMuPDF version to be 1.18.15 for in-house compatibility issues.
=> fix: pymupdf version

doctr/models/detection/differentiable_binarization/base.py
This PR provides an heuristic to determine the quadrant of the document (only 2 quadrants are allowed, +90 and -90 with respect to the horizontal). The quadrant is determined with the median aspect ratio of cv2 min area rect, and then we can rectify boxes knowing the quadrant.
This is not a long-term fix, we should add a classifier to resolve the angle of each box perfectly, but for the moment I couldn't find anything else to fix this issue.
=> fix: box angle rectification according to the quadrant

doctr/models/builder.py, tests/common/test_models_builder.py
This PR improves the line resolution heuristic: when we build a document with rotated boxes, lines are resolved the right way (with a rotation of the page).
=> feat: add line resolution for rotated boxes

references/classification/train_tensorflow.py, references/detection/train_tensorflow.py, references/recognition/train_tensorflow.py
This PR adds support of AMP for TensorFlow training scripts following this documentation: https://www.tensorflow.org/guide/mixed_precision.
Checking within the script, all modules and operations are indeed running the "mixed_float16" policy, but for some reasons, I haven't noticed any RAM saving on GPU :man_shrugging: 
Please note that some TF models still have issues with AMP (cf. https://github.com/tensorflow/tensorflow/issues/53345) but this PR enables it for training generally speaking.
Closes #263
=> feat: Added option to use AMP with TF scripts

.github/workflows/style.yml, .pydocstyle, CONTRIBUTING.md, Makefile, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py, doctr/utils/fonts.py, doctr/utils/metrics.py, doctr/utils/visualization.py, setup.py, tests/common/test_requirements.py
- added config for `pydocstyle`
- added deps in setup.py, updated CONTRIBUTING & Makefile
- added a CI job to run pydocstyle
- fixed docstrings that were posing problems
=> docs: Added minimal docstring sanity check

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/linknet/pytorch.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/master/pytorch.py
This PR fixes the initialization when the feature extractor already has defined param values. Before this PR, those values were overridden with a param initialization, and this PR prevents this (for `pretrained_backbone=True` to work correctly).
cf. #591 
=> fix: Fixed param override of backbone

references/detection/train_pytorch.py, references/recognition/train_pytorch.py
This PR simply adds the missing AMP flags to enable it on all training & evaluation loops for PyTorch.
=> fix: Added missing AMP flags in training scripts

doctr/datasets/doc_artefacts.py, doctr/io/pdf.py, doctr/models/_utils.py, doctr/utils/metrics.py, tests/common/test_models.py
This PR fixes the multiple deprecation warnings from PyMuPDF & numpy by using the recommended replacement.
=> fix: Fixed deprecation warnings from numpy & PyMuPDF

doctr/models/recognition/predictor/_utils.py
- filters out chunked crops that are 0-sized in `split_crops` (cf. the error in https://github.com/mindee/doctr/runs/4475225188?check_suite_focus=true)
- adds the function docstring
=> fix: Added a 0-sized crop safeguard in split_crops

doctr/models/obj_detection/__init__.py, doctr/models/obj_detection/faster_rcnn/__init__.py, doctr/models/obj_detection/faster_rcnn/pytorch.py, references/obj_detection/train_pytorch.py, tests/pytorch/test_models_obj_detection_pt.py
- adds `fasterrcnn_mobilenet_v3_large_fpn` as supported architecture for PyTorch
- adds corresponding unittests
- updates training script accordingly (and adding AMP support)
=> feat: Added support of FasterRCNN for PyTorch

doctr/transforms/modules/pytorch.py
This PR fixes the second part of the unittest failures: now that we're positive no crop is 0-sized, in rare cases, preserving the aspect ratio can lead to a 0-sized intermediate image size. 
This should not be encountered for trained models but this PR adds a clipping to 1 pixel in case this happens!
=> fix: Added safeguard for extreme aspect ratio in Resize

doctr/datasets/datasets/base.py
This PR adds the flexibility to override the cache folder used by `VisionDataset`, which makes it possible to have a flexible monkeypatch strategy for unittests.
cc @felixdittrich92
=> feat: Added possibility to change the cache dir of datasets

doctr/utils/geometry.py, tests/common/test_utils_geometry.py
- fixes the cv2 conventions of angle orientation for polygon <--> rbox conversions
- updates unittests
The following snippet:
```python
import numpy as np
import matplotlib.pyplot as plt
from doctr.utils.geometry import rbbox_to_polygon
def plot_points(points):
img = np.zeros((200, 150))
for point in points.round().astype(int):
img[point[1], point[0]] = 1
plt.imshow(img); plt.show()
plot_points(rbbox_to_polygon((100, 100, 40, 10, 45.)))
```
was producing
and now produces
Additionally this snippet:
```python
import numpy as np
import matplotlib.pyplot as plt
from doctr.utils.geometry import rbbox_to_polygon, fit_rbbox
angles = np.arange(-90, 91)
rboxes = [fit_rbbox(rbbox_to_polygon((100, 100, 40, 10, angle)))for angle in angles] …
```
=> fix: Fixed geometry utils for polygon <--> rbox conversions

doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/linknet/base.py, tests/pytorch/test_models_detection_pt.py, tests/tensorflow/test_models_detection_tf.py
- fixes the `build_target` polygon conversion for LinkNet & DBNet when rotated targets are used
- adds a test case for rotated targets
- reduces the input size in unittest from 1024 to 512 to speed up the test & ease the RAM
=> fix: Fixed build_target for detection models with rotated targets

references/classification/train_pytorch.py, references/classification/utils.py, references/detection/train_pytorch.py, references/detection/utils.py, references/obj_detection/train_pytorch.py, references/obj_detection/utils.py, references/recognition/train_pytorch.py, references/recognition/utils.py
Following up on #478, this PR adds a LR finder feature in all PyTorch training scripts
Here is how it renders for artefact detection:
=> feat: Added LR finder option in PyTorch training scripts

docs/source/io.rst, doctr/io/pdf.py, tests/common/test_io.py
- adds `get_lines` methods on PDF objects to aggregate words into lines on source PDFs
- adds unittest
- adds entry in the documentation
=> feat: Added line reading for source PDFs

doctr/models/detection/differentiable_binarization/base.py, doctr/utils/geometry.py, doctr/utils/visualization.py, tests/common/test_utils_geometry.py
This PR fixes the following:
- angle computation in visualization.py
- angle computation in fit_rbbox
- Polygon expansion for rbbox: before this PR, we computed the area & perimeter of the polygon for the Vatti clipping algorithm from the raw polygon, now we compute it from the rotated rectangle which is more accurate and allow us to match the boxes when we have assume_straight_pages = False and assume_straight_pages = True.
before:
now:
=> fix: box computing when assume straight pages is false

tests/tensorflow/test_models_detection_tf.py
This PR fixes the tolerance threshold for the loss difference between straight & rotated bboxes
=> test: Fixed TF loss unittest

doctr/models/obj_detection/faster_rcnn/pytorch.py, tests/pytorch/test_models_obj_detection_pt.py
This PR adds a checkpoint for artefact detection.
Any feedback is welcome:)
=> feat: Added checkpoint for obj_detection

doctr/utils/metrics.py, tests/common/test_utils_metrics.py
- updates the expected mean IoU value in unittests
- fixes the computation of `tot_iou` in metrics which is used for Mean IoU: it was taking the max IoU across all preds for a given GT, while it's supposed to take the max IoU across all GTs for a given pred.
=> fix: Fixed computation of Mean IoU

doctr/models/_utils.py, tests/common/test_io.py, tests/conftest.py, tests/pytorch/test_models_zoo_pt.py, tests/tensorflow/test_models_detection_tf.py, tests/tensorflow/test_models_zoo_tf.py
- seeing that CI takes sometimes a long time to download the initial PDF, this PR mocks it completely to avoid data transfer
- updates impacted unittests
This speeds up the unittests of models and avoids CI failure when the URL is unreachable.
=> test: Switch to a fully mocked PDF for unittests

doctr/datasets/loader.py, references/classification/train_tensorflow.py, references/detection/train_tensorflow.py, references/recognition/train_tensorflow.py
- to stick closer to the PyTorch implementation, the DataLoader arg "workers" was renamed into "num_workers"
- reflected changes on training scripts
=> refactor: Renamed DataLoader arg "workers" into "num_workers"

demo/app.py, doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/differentiable_binarization/tensorflow.py, doctr/models/detection/linknet/pytorch.py, doctr/models/detection/linknet/tensorflow.py, doctr/models/detection/predictor/pytorch.py, doctr/models/detection/predictor/tensorflow.py, tests/pytorch/test_models_detection_pt.py, tests/tensorflow/test_models_detection_tf.py
- ensures all prediction call flags are named the same way ("return_boxes" --> "return_preds")
- reflected changes on unittests, and demo
=> refactor: Unified return_preds flags across all tasks

tests/conftest.py
This PR silences the deprecation warnings from PyMuPDF.
=> test: Silenced PyMuPDF warnings

references/detection/train_pytorch.py, references/detection/train_tensorflow.py
This PR fixes an issue introduced by #741 with the change of flags in the model call.
=> fix: Fixed detection training script

.github/workflows/references.yml, doctr/models/detection/linknet/tensorflow.py, references/detection/latency.csv, references/detection/latency_pytorch.py, references/detection/latency_tensorflow.py, references/obj_detection/latency.csv, references/obj_detection/latency_pytorch.py, references/recognition/latency.csv, references/recognition/latency_pytorch.py, references/recognition/latency_tensorflow.py
As per #699, some latency benchmarking was required. This PR introduces scripts in PyTorch & TensorFlow to benchmark latency on CPU & GPU for text recognition and text detection.
The results were added in a csv file in the same folder to keep track of latency changes for each model.
Finally, a CI job was added to ensure those scripts can run properly.
=> feat: Added latency evaluation scripts for all tasks

doctr/models/detection/linknet/base.py
This PR simply updates the binary threshold of LinkNet which was the same as in the DBNet. But with the difference in the LinkNet loss, 0.15 is way too low. This modification gives a boost on text detection evaluation.
=> fix: Fixed the bin_thresh of LinkNet

tests/pytorch/test_models_detection_pt.py
Some of our unittests involve random inputs, and the check of similarity between the values of the loss on straight boxes vs rotated ones has failed quite a lot. This PR increases the threshold to avoid that problem.
=> test: Increased flexibility of loss test

doctr/datasets/classification/base.py, doctr/datasets/cord.py, doctr/datasets/datasets/base.py, doctr/datasets/detection.py, doctr/datasets/doc_artefacts.py, doctr/datasets/funsd.py, doctr/datasets/ic03.py, doctr/datasets/ic13.py, doctr/datasets/iiit5k.py, doctr/datasets/ocr.py, doctr/datasets/recognition.py, doctr/datasets/sroie.py, doctr/datasets/svhn.py, doctr/datasets/svt.py, doctr/datasets/synthtext.py, doctr/models/detection/differentiable_binarization/base.py, doctr/models/predictor/base.py, doctr/transforms/modules/base.py, references/classification/train_pytorch.py, references/classification/train_tensorflow.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/obj_detection/train_pytorch.py, references/recognition/train_pytorch.py, references/recognition/train_tensorflow.py, tests/common/test_datasets.py, tests/common/test_transforms.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
Following up on #352, this PR introduces the following modifications:
- renames "sample_transforms" into "img_transforms" to be more explicit (hesitated with "input_transforms" but we only cover Vision, so I don't think it's necessary)
- adds "sample_transforms" which are performed after "img_transforms" on both the image and the target
- reflected changes in datasets, unittests and training scripts
- added `SampleCompose` (to compose sample_transforms) and `ImgTransformation` (to wrap an img_transform as a sample_transform) utils
- added dedicated unittests
With this PR, the way to pass thransforms becomes the following:
- if you only have transformations that don't modify the target, pass them as `img_transforms`
- if you have both, there are two options:
- passing the image …
=> refactor: Introduces img + target transforms in Datasets

doctr/models/detection/differentiable_binarization/base.py
This PR simply fixes the segmentation mask building: I believe we have never entered that loop, because considering its shape, it's impossible that it would have worked.
=> fix: Fixed mask computation of DBNet

.github/workflows/references.yml, references/classification/README.md, references/classification/train_pytorch.py, references/detection/README.md, references/detection/train_pytorch.py, references/obj_detection/train_pytorch.py, references/recognition/README.md, references/recognition/train_pytorch.py
- removes the Pytorch to force params in a contiguous chunk to speed up optimization (now it's included in the core library)
- updates the CI & documentation accordingly
- removes unneeded loader operations in training scripts
=> refactor: Removed contiguous param since it's included in torch>=1.7

docs/source/transforms.rst, doctr/datasets/classification/base.py, doctr/datasets/classification/pytorch.py, doctr/datasets/classification/tensorflow.py, doctr/transforms/modules/tensorflow.py, references/classification/train_pytorch.py, references/classification/train_tensorflow.py, tests/tensorflow/test_transforms_tf.py
- adds an implementation of GaussianBlur for TensorFlow using tf addons 
- adds the possibility to pick a random font in a list for CharGenerator
- improved `synthesize_txt_img` to automatically resolve the font size and image size depending on the text
- updates character classification training scripts to add more augmentations
- fixed the validation set of char classification (by default, without color inversion, the images had a black background and text in white all the time, I switched the split to 90% of white background + dark text)
This PR was used to retrain all PyTorch classification models successfully, and TensorFlow are ongoing.
=> feat: Adds GaussianBlur, random font for CharGenerator and improves training scripts

references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, references/detection/results.csv
- adds scripts to evaluate text detection models on supported datasets
- adds the perf report as a .csv
I'll have to open another PR for text recognition because the crop needs to be made live efficiently. Those PRs aim at speeding up evaluation runs for models once they are trained
=> feat: Added dedicated evaluation scripts for text detection

doctr/io/elements.py, doctr/models/zoo.py, doctr/utils/visualization.py
This PR allows to use the `preserve_aspect_ratio` flag in the predictor:
```
model = ocr_predictor(pretrained=True, assume_straight_pages=False, preserve_aspect_ratio=True)
doc = DocumentFile.from_images(path)
result = model(doc)
result.show(doc, preserve_aspect_ratio=True)
```
Yields:
Instead of:
=> feat: add preserve aspect ratio to predictor and vizualisation utils

tests/tensorflow/test_models_zoo_tf.py
This PR reduces the number of crops processed in unittests by using a pretrained detection model. It changed the number of crops from several thousands to a maximum of a few dozens.
It also prevents degraded localization candidates, and will hopefully fix the ongoing issue with current PR unittests in TensorFlow.
=> test: Fixed TensorFlow predictor unittest

references/classification/latency_pytorch.py, references/classification/latency_tensorflow.py, references/detection/latency_pytorch.py, references/detection/latency_tensorflow.py, references/obj_detection/latency_pytorch.py, references/recognition/latency_pytorch.py, references/recognition/latency_tensorflow.py
This PR simply replaces `time.time()` with `time.perf_counter()` which is much more recommended for latency benchmarks.
=> feat: Updated timing to more accurate one

docs/source/transforms.rst, doctr/transforms/modules/tensorflow.py, tests/tensorflow/test_transforms_tf.py
This PR adds the following changes to the existing repo:
- It adds Gaussian Noise augmentation implementation in Tensorflow
-  It adds a unittest for the same in Tensorflow
- Added GaussianNoise in the documentation
=> feat: Added Gaussian Noise implementation in Tensorflow

doctr/transforms/functional/base.py, doctr/transforms/functional/pytorch.py, doctr/transforms/functional/tensorflow.py, tests/pytorch/test_transforms_pt.py, tests/tensorflow/test_transforms_tf.py
- fixed the box cropping part of RandomCrop: a previous PR fixed the cropping of the image, but there was some offset left to correct and some rescaling to do
- updated unittests to avoid missing this next time
- took the liberty of refactoring numpy part into a shared `crop_boxes` function to avoid duplication
=> fix: Fixed the box cropping from RandomCrop

.github/workflows/references.yml
This PR simply changes the architecture to train in the CI job since mobilenet V3 has grouped convolutions for which TF does not support backprop on CPU :man_shrugging: 
=> ci: Fixed CI training job for TF

doctr/transforms/modules/pytorch.py, references/obj_detection/train_pytorch.py, tests/pytorch/test_transforms_pt.py
- It adds Random horizontal Flip as an augmentation that transforms images as well as the labels.
from doctr.transforms import RandHorizontalFlip
import torch
transformed = RandHorizontalFlip(p = 0.5)
target = {"boxes": [ [0.1, 0.1, 0.4, 0.5] ], "labels": [1]}
image, target = transformed(torch.rand((3, 224, 224)), target)
- It adds a uniitest for the same
=> feat: Added Random Horizontal Flip augmentation

.github/process_commit.py, .github/release.yml, .github/workflows/pr-labels.yml
- adds a github action that will ping PR mergers if no valid labels have been added
- adds a release template
=> ci: Added release helper actions

README.md, docs/source/_static/js/custom.js, docs/source/index.rst
- fixed the hyperlinks to the documentation in the README
- adds the new datasets to the list on the documentation landing page
- fixed the version display on the documentation: when accessing a subtag of a page, the URL included a part `.html#mytag` and the parser was failing to show the correct part. This is now fixed
=> docs: Fixed README link & update documentation

doctr/datasets/cord.py, doctr/datasets/datasets/base.py, doctr/datasets/datasets/pytorch.py, doctr/datasets/datasets/tensorflow.py, doctr/datasets/detection.py, doctr/datasets/funsd.py, doctr/datasets/ic13.py, doctr/datasets/iiit5k.py, doctr/datasets/ocr.py, doctr/datasets/sroie.py, doctr/datasets/svhn.py, doctr/datasets/synthtext.py, doctr/datasets/utils.py, doctr/io/image/pytorch.py, doctr/io/image/tensorflow.py, doctr/utils/geometry.py, tests/common/test_utils_geometry.py, tests/conftest.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
Following up on #750, this PR introduces the following modifications:
- adds a pre_transforms mechanism to perform conversion before any transformation
- adds a abs coord to rel coords function (for both boxes & polygons)
- uses both of these to switch all geometry targets to relative coords
- adds corresponding unittests
- fixed FUNSD when `use_polygons=True`
- fixed `OCRDataset` straight boxes
- added option `use_polygons` in `OCRDataset`
Overrules #702 (cc @felixdittrich92)
=> refactor: Enforced relative coordinates for all dataset geometries

doctr/transforms/functional/pytorch.py, doctr/transforms/functional/tensorflow.py, doctr/transforms/modules/base.py, doctr/utils/geometry.py, tests/pytorch/test_transforms_pt.py, tests/tensorflow/test_transforms_tf.py
Following the refactoring of rotation, some edge cases weren't handled. This PR restarts fresh and introduces the following modifications:
- deleted `rotate` to introduce `rotate_sample`
- the function can take boxes or polygons, with or without expansion
- unittests were considerably extended to avoid further issues
- added box filtering in `RandomRotate`
Here is a snippet to show this:
```python
from doctr.transforms.functional import rotate_sample
import matplotlib.pyplot as plt
import numpy as np
import torch
img = torch.ones((3, 200, 100), dtype=torch.float32)
h, w = img.shape[1:]
box = np.array([0, 0, .5, .25])[None, ...]
target = np.zeros((*img.shape[1:], 3), dtype=np.uint8)
for xmin, ymin, xmax, ymax in box:
target[int(ymin * h): int(ymax * h), int(xmin * w): int(xmax * w)] = …
```
=> fix: Fixed rotation of img + target

references/detection/utils.py
this PR fixes the show_sample function when the batch size is 1
=> fix: show sample when batch size is 1

.github/verify_pr_labels.py, .github/workflows/pr-labels.yml
In order to better automate release notes, this PR fixes the PR label check action.
To illustrate this, I didn't add all required labels to this PR (needs one of the primary labels, AND one of the secondary labels defined in https://github.com/mindee/doctr/blob/pr-labels/.github/verify_pr_labels.py). Once merged, the bot will ping me (since I will merge it) to remind me to correctly label the PR.
=> ci: Fixed PR label check job

.github/workflows/pr-labels.yml
This PR fixes the ref to the script used to verify the labels.
I forgot one label on purpose on this PR so that the bot will comment on this one :+1: 
=> ci: Fixed typo in the script ref

doctr/models/detection/predictor/pytorch.py, doctr/models/recognition/predictor/pytorch.py
This PR simply adds a dynamic device selection for predictor inference.
This snippet:
```python
import os
os.environ['USE_TORCH'] = '1'
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
doc = DocumentFile.from_pdf('/path/to/sample.pdf').as_images()
predictor = ocr_predictor(pretrained=True).cuda()
out = predictor(doc)
```
used to yield:
```
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```
because the model is on cuda, while the inputs are never moved to GPU.
And now, the snippet executes perfectly (& much faster than on CPU)
Since the predictions returned by each postprocessor are in numpy (automatically moved to CPU), this doesn't break any …
=> feat: Added support of GPU for predictors in PyTorch

doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/models/zoo.py, tests/pytorch/test_models_zoo_pt.py, tests/tensorflow/test_models_zoo_tf.py
- simply saves a bit of memory by avoiding to instantiating the crop orientation predictor when it will never be used.
- refactors predictor constructor (moving as many things as possible to base): that way, kwargs of `DocumentBuilder` can be directly passed to the high-level API `ocr_predictor`
- updates unittests to check that the crop orientation predictor is only there when needed
=> refactor: Avoids instantiating orientation predictor when unnecessary

doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, scripts/evaluate.py
This PR adds a straight-eval  arg in the evaluate script to allow using the metrics with straight bounding boxes while using a detection predictor working with polygons (assume straight pages can be False).
I also fixed a bug in the predictor to cast to numpy before calling the extraction function (when we use a dataset we have tf/pt tensors otherwise)
=> feat: add straight-eval arg in evaluate script

doctr/models/_utils.py, doctr/utils/geometry.py, tests/common/test_utils_geometry.py
This PR fixes the polygon orientations, which was bot left, top left, top rigth, bot right instead of top left, top rigth, bot right, bot left.
This fixes the line aggregation.
=> fix: polygon orientation + line aggregation

doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/utils/geometry.py, tests/common/test_models.py, tests/common/test_utils_geometry.py, tests/conftest.py, tests/tensorflow/test_models_zoo_tf.py
This PR is to address #800 as part of #788. 
It restores the function `remap_boxes` from #488 and adds a new functionality test to verify the output of a pretrained predictor on a rotated document.
=> Restore remap boxes

doctr/models/recognition/sar/pytorch.py
Following up on #802, this PR introduces the following changes:
- fixes a major typo in the loss computation (the sequence masking was inverted)
- cleaned encoder and decoder for a much more understandable version
I tried training the model with the synthetic training set, and a real-world validation set and managed to reach almost 100% of exact match after a few epochs.
=> fix: Fixed SAR model for training and inference in PyTorch

docs/source/transforms.rst, doctr/transforms/functional/base.py, doctr/transforms/functional/pytorch.py, doctr/transforms/functional/tensorflow.py, doctr/transforms/modules/pytorch.py, doctr/transforms/modules/tensorflow.py, tests/pytorch/test_transforms_pt.py, tests/tensorflow/test_transforms_tf.py
Following up on #730, this PR introduces the following modifications:
- adds `RandomShadow` augmentation
- adds unittests
- adds documentation
The following snippet:
```python
import matplotlib.pyplot as plt
from doctr.io.image import read_img_as_tensor
from doctr.transforms import RandomShadow
transform = RandomShadow((.2, .8))
img = read_img_as_tensor("path/to/your/image.jpg")
plt.imshow(transform(img).numpy()); plt/axis('off'); plt.show()
```
yields:
Briefly:
- this first creates a 4-point polygon with 1 side on the top edge of the image
- the polygon is rotated & expanded
- the polygon is filled with 1s
- we apply an intensity gradient (so that the shadow fades as we go further from the source)
- with TF or PyTorch we overlay this after applying gaussian blur (a sharp shadow is not …
=> feat: Added shadow augmentation for all backends

doctr/transforms/functional/base.py, doctr/transforms/modules/pytorch.py, doctr/transforms/modules/tensorflow.py, tests/common/test_transforms.py, tests/pytorch/test_transforms_pt.py
- fixed expand_line for vertical & horizontal lines
- adds clipping when using float in both frameworks
- added unittests for expand_line
_This fixes the randomly failing test we sometimes have on PRs_
=> fix: Fixed expand_line for horizontal & vertical cases

doctr/models/obj_detection/factory/__init__.py, doctr/models/obj_detection/factory/pytorch.py, doctr/models/obj_detection/faster_rcnn/pytorch.py, mypy.ini, requirements-pt.txt, requirements.txt, setup.py, tests/common/test_headers.py, tests/pytorch/test_models_obj_detection_pt.py, tests/tensorflow/test_transforms_tf.py
Following up on #426, this PR introduces the following modifications:
- refactored faster rcnn
- added a `from_hub` function to load artefact detection architectures in PyTorch
- added unittest
- fixed header unittest
With PyTorch backend, the following snippets are completely equivalent:
```python
from doctr.models.obj_detection import fasterrcnn_mobilenet_v3_large_fpn
model = fasterrcnn_mobilenet_v3_large_fpn(pretrained=True)
```
```python
from doctr.models.obj_detection.factory import from_hub
model = from_hub("mindee/fasterrcnn_mobilenet_v3_large_fpn")
```
=> feat: Added loading method for PyTorch artefact detection models from HF Hub

docs/source/using_models.rst
This PR specifiy args to pass to predictors to work with rotated documents in the docs, and provides some snippets.
Closes #807
=> docs: add rotation in docs

doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/models/zoo.py, tests/tensorflow/test_models_zoo_tf.py
This PR adds the option to preserve aspect ratio of the pages in the whole OCRPredictor pipeline, which leads to much better results on the detection task. 
=> feat: add aspect ratio for ocr predictor

doctr/datasets/datasets/pytorch.py, doctr/datasets/datasets/tensorflow.py, tests/common/test_datasets.py
- updates `_read_sample` to return a deepcopy of the target to prevent inplace modifications
- adds a dedicated unittest (accessing several times a specific target will return the same value each time now, whether there are inplace transforms or not)
Closes #840
=> fix: Fixes inplace target modifications for AbstractDatasets

docs/source/index.rst, docs/source/models.rst
- fixed the indentation of the paper list on the landing page
- fixed the underline of a section's subtitle
cc @felixdittrich92 (since this was completely independent from the rest)
=> fix: Fixed landing page and title underlines

docs/source/conf.py
With the new documentation theme, the HTML page title (the one appearing on tabs) is now "docTR 0.5.0a0-git documentation" which isn't very user-friendly. This PR sets it as "docTR documentation" (on the former theme, we had "docTR: Document Text Recognition documentation - v0.5.0a0-git")
=> docs: Fixed HTML title

demo/app.py, doctr/models/detection/linknet/base.py, doctr/utils/visualization.py
This PR adjusts the Linknet parameters in the postprocessing to have better performances, and includes the `linknet_resnet18_rotation` model in the streamlit demo. Pages are rendered only for straight models (for now), and we don't write the words above each boxes if the model is a rotation model.
This demo will be improved later, but for the moment it allows anyone to quickly see the performances of our rotation model without modifying the behavior for all other models.
This is how it renders for the demo:
=> fix: linknet hyperparameters postprocessing + demo for rotation model

doctr/datasets/vocabs.py
I added vietnamese VOCABS for Vietnamese devs if they want to use doctr for vietnamese like me :)
=> feat: Added Vietnamese entry in VOCAB

docs/source/getting_started/installing.rst
Hey there 👋 
I noticed a small typo introduced in #862 for installation instructions. This PR simply fixes that for both tabs.
=> docs: Fixed typo in installation instructions

doctr/models/classification/magc_resnet/pytorch.py, doctr/models/classification/mobilenet/pytorch.py, doctr/models/classification/resnet/pytorch.py, doctr/models/classification/vgg/pytorch.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/utils/pytorch.py, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_utils_pt.py
Following up on #874, this PR introduces the following modifications:
- renamed "pop_entrys" to "ignore_keys"
- updated `load_pretrained_params` to avoid non-strict loading of wrongly sized state_dict
- fixed classification models `ignore_keys` mechanism (the keys to ignore were hardcoded in the factory function, while this function is used to build models of different size, and thus with Linear layers being named differently)
- added dedicated unittest for `ignore_keys`
=> fix: Fixed load_pretrained_params in PyTorch when ignoring keys

.github/workflows/docker.yml
Following up on #847, this PR introduces the following modification:
- adds a step in CI job for API, to ping the swagger before running the unittest
Presumably, if the behaviour described in #847, the CI should fail on this PR.
=> ci: Add swagger ping in API CI job

doctr/models/utils/pytorch.py, doctr/models/utils/tensorflow.py, mypy.ini, references/classification/train_tensorflow.py, requirements.txt, setup.py, tests/conftest.py, tests/pytorch/test_models_classification_pt.py, tests/tensorflow/test_models_classification_tf.py
Export for TF classification models
- function for easy exporting (similar to PT) and corresponding tests
- minor renaming
- adds tf2onnx on TF side
- include export ability in classification training script
NOTE: test excludes magc_resnet31 currently there are some problems: 
```
```
All other models works fine.
Issue:
#789 
=> [onnx/tf] classification models export 

doctr/datasets/utils.py
This PR improves the error message of `encode_string` when a character is not to be found in the vocab.
Closes #927
=> docs: Improved error message of encode_string

doctr/models/recognition/sar/pytorch.py
This PR:
- reverts pooling to fix onnx export (retrained with same results as before)
- set attention units to 512 as described in paper (fix my mistake ^^)
- some formatting / docu
(functional pooling has raised some ONNX export issues)
=> [Refactor] PyTorch SAR_Resnet31 make it ONNX exportable (again)

doctr/models/classification/resnet/tensorflow.py, doctr/models/recognition/sar/tensorflow.py
This PR: (Still in progress :))
- fix SARDecoder forward step
Issue:
#802
=> [Fix] TensorFlow SAR_Resnet31 implementation

README.md
Fix links to text detection and text recognition in readme
=> Fix links in readme 

doctr/models/recognition/master/pytorch.py, doctr/models/recognition/transformer/pytorch.py
This PR:  (Still in progress)
some notes at the moment:
different from paper input set to our default (32, 128)
ftm: transformer plain implementation not nn modules
but training and inference works fine :sweat_smile: 
@frgfm feel free to grab this and take a look :+1: 
Issue:
#802
=> [Fix] PyTorch MASTER implementation

.github/workflows/references.yml, doctr/datasets/utils.py, references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, references/recognition/evaluate_pytorch.py, references/recognition/evaluate_tensorflow.py
This PR contains:
- ensure all crops are RGB
- updates detection eval scripts 
- adds recognition eval scripts
- add CI jobs for recognition and detection evaluation scripts
=> [references] Add eval recognition and update eval detection scripts 

setup.py
This PR simply adds a reference to the reason behind the keras version specifier.
cf #932
=> docs: Documentation the reason for keras version specifier

doctr/datasets/mjsynth.py
This PR:
- filter corrupted or missing images
Please merge #954  before this one :)
=> [Fix] MJSynth dataset: filter corrupted or missing images

doctr/datasets/svt.py
This PR:
- clip box values and add shape and label check
Please merge #954 before this one :)
=> [Fix] SVT dataset: clip box values and add shape and label check

.github/workflows/references.yml, requirements.txt, setup.py, tests/tensorflow/test_models_classification_tf.py
- updates TF version specifier above 2.9 to fix #454
- removes keras version specifier since this was only relevant for TF versions until 2.7
- switched back architecture for classification training CI job from resnet18 to mobilenet (to make sure that #454 is fixed, which is how we found out)
Closes #454
=> chore: Updated TF requirements to fix grouped convolutions on CPU

doctr/models/classification/magc_resnet/tensorflow.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py, doctr/models/recognition/transformer/pytorch.py, doctr/models/recognition/transformer/tensorflow.py
This PR:
- refactored tensorflow transformer implementation
- fix MASTER Decoder
@charlesmindee @frgfm feel free to take a first look some improvements are very welcome :D
Todo:
Issue:
#802
=> [Fix] Tensorflow MASTER implementation

doctr/models/utils/pytorch.py, doctr/models/utils/tensorflow.py, references/classification/train_pytorch.py, references/classification/train_tensorflow.py, tests/pytorch/test_models_classification_pt.py, tests/tensorflow/test_models_classification_tf.py
This PR:
- updates current onnx export for further processing in Part2 
Part2 : add slow tests (only local testing) for each model
=> [ONNX] Part1: update current onnx export 

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/differentiable_binarization/tensorflow.py, doctr/models/detection/linknet/pytorch.py, doctr/models/detection/linknet/tensorflow.py, tests/pytorch/test_models_detection_pt.py, tests/tensorflow/test_models_detection_tf.py
This PR:
- adds test cases to ensure all detection models can be exported into ONNX format in both frameworks
- update missing docstrings
NOTE: Part2 is splitted in detection and recognition
slow tests will be introduced with the recognition test PR 
Issues:
#789 #790
=> [ONNX/Tests] Part2 add ONNX tests for TF and PT detection models

Makefile, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/crnn/tensorflow.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/master/tensorflow.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/sar/tensorflow.py, tests/pytorch/test_models_recognition_pt.py, tests/tensorflow/test_models_recognition_tf.py
This PR:
- adds test cases to ensure all recognition models can be exported into ONNX format in both frameworks
Note: MASTER PT can be exported but not loaded with onnxruntime there is an internal ticket i have linked it in the test
- introduces slow tests which are only tested on local machine (to ensure CI instance will not be killed :sweat_smile: )
Issues:
#789 #790
=> [ONNX/Tests] Part2 add ONNX tests for TF and PT recognition models 

.github/workflows/references.yml, doctr/datasets/cord.py, doctr/datasets/funsd.py, doctr/datasets/svhn.py, references/recognition/evaluate_pytorch.py, references/recognition/evaluate_tensorflow.py
This PR:
- reverts the whitespace filtering in FUNSD and CORD (is to much focused then to be used only inside docTR)
- update recognition eval scripts and corresponding CI job ( batch_size = 1 as default to ensure nothing is skipped in fact of whitespaces seperated labels)
- add fix for svhn dataset (recognition)
Any feddback is welcome :hugs:
=> [datasets] revert whitespace filtering and fix svhn reco

docs/source/modules/models.rst, docs/source/using_doctr/using_models.rst
This PR aims to:
* modify dead links from the documentation in https://mindee.github.io/doctr/using_doctr/using_models.html such as https://mindee.github.io/doctr/using_doctr/models.html#doctr.models.detection.linknet_resnet18.
* add `db_resnet50_rotation` and `linknet_resnet18_rotation` in https://mindee.github.io/doctr/modules/models.html
* update one code block with 4 spaces
=> Update docs in `using_doctr`

scripts/analyze.py, scripts/detect_artefacts.py, scripts/detect_text.py
A script to extract text from files.
=> feat: add a basic example of text detection

.github/workflows/docker.yml, api/requirements.txt, api/tests/conftest.py
This PR aims two solve problems:
* to fix this error on CI : https://github.com/mindee/doctr/runs/7517599231?check_suite_focus=true
`curl` command in CI is run but the API is not fully ready so the `Ping server` step often failed. There is an option `--retry-all-errors` since curl 7.71.0 but there is only curl 7.68.0 on `ubuntu-latest` (which is ubuntu 20.04) and that's not that simple to update curl to this version.
I replaced `curl` by `wget` with option `--spider`.
From man page:
```
--spider
When invoked with this option, Wget will behave as a Web spider, which means that it will not download the pages, just check that they are there.
```
* fix https://github.com/mindee/doctr/issues/847. The problem comes from Tuples on fastapi, see https://github.com/tiangolo/fastapi/issues/4168, …
=> pytest-api test: fix ping server step

docs/source/index.rst
This PR fixes two types on the documentation landing page.
=> docs/index: fix two minor typos

doctr/datasets/loader.py, doctr/models/preprocessor/pytorch.py, doctr/models/preprocessor/tensorflow.py, doctr/utils/multithreading.py, tests/common/test_utils_multithreading.py
`multithread_exec` function returned result of different types depending on number of threads: if it's lesser than 2 - `Iterator`, otherwise - `list`.
In every place this function is used, result is expected to be of type `list` and it fails if result is an `Iterator`.
With this change function would always return `Iterator` to let user decide which type to convert it to.
=> Changed return type of multithread_exec to iterator

doctr/datasets/imgur5k.py, doctr/datasets/synthtext.py
This PR:
- fixes the mem issue for SynthText and IMGUR5K Recognition 
- now we write a new dataset for both datasets to disk (fastest way)
related to:
#935    Fix for Recognition: SynthText and IMGUR5K (not beauty but it works well - no mem issue and whole speed up)
=> [datasets] Fix recognition parts of SynthText and IMGUR5K

doctr/datasets/cord.py, doctr/datasets/datasets/pytorch.py, doctr/datasets/datasets/tensorflow.py, doctr/datasets/funsd.py, doctr/datasets/ic03.py, doctr/datasets/ic13.py, doctr/datasets/iiit5k.py, doctr/datasets/imgur5k.py, doctr/datasets/mjsynth.py, doctr/datasets/sroie.py, doctr/datasets/svhn.py, doctr/datasets/svt.py, doctr/datasets/synthtext.py, references/recognition/evaluate_pytorch.py, references/recognition/evaluate_tensorflow.py, tests/common/test_datasets.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
This PR:
- revert mistake for recognition dataset parts (img, label) instead of (img, dict)
- add target check in _read_sample
- now we have two cases in the library for datasets 
- more than one annotation type: targets has to be a dict with boxes / labels keys
- only one annotation type: target has to be str (label) or np.ndarray (boxes)
Hopefully that this is now a match to avoid mistakes for transformations
Closes:
#935
=> [Fix] unify recognition dataset parts return signature

doctr/models/classification/predictor/pytorch.py
This PR:
- fix moving rotation classifier input to cuda device if given
Closes:
#1020
=> [Fix] rotation classifier input move to model device

references/recognition/README.md
As per discussion #1046 a small description of how to train using custom fonts has been added to the README.md of references/recognition.
=> Updated README.md for custom fonts

docs/source/modules/models.rst, doctr/models/classification/__init__.py, doctr/models/classification/vit/__init__.py, doctr/models/classification/vit/pytorch.py, doctr/models/classification/vit/tensorflow.py, doctr/models/classification/zoo.py, doctr/models/modules/__init__.py, doctr/models/modules/transformer/pytorch.py, doctr/models/modules/transformer/tensorflow.py, doctr/models/modules/vision_transformer/__init__.py, doctr/models/modules/vision_transformer/pytorch.py, doctr/models/modules/vision_transformer/tensorflow.py, references/classification/train_tensorflow.py, tests/pytorch/test_models_classification_pt.py, tests/tensorflow/test_models_classification_tf.py
This PR:
- adds ViT as classification model, which can be used as backbone for ViTSTR/ParSeq
Any feedback or ideas for improvements are very welcome :hugs: 
validated via test runs both models trains well
=> add ViT as classification model TF and PT

doctr/models/classification/vit/pytorch.py, tests/pytorch/test_models_factory.py, tests/tensorflow/test_models_factory.py
This PR:
- adds missing model tests hf hub
- fix missing cfg in pytorch vit  / fixes also upload pytorch vit to hub
=> [tests] add missing hf model tests

docs/source/modules/models.rst, doctr/models/classification/vit/pytorch.py, doctr/models/classification/vit/tensorflow.py, doctr/models/classification/zoo.py, doctr/models/modules/transformer/pytorch.py, doctr/models/modules/transformer/tensorflow.py, doctr/models/modules/vision_transformer/pytorch.py, references/classification/train_tensorflow.py, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_factory.py, tests/tensorflow/test_models_classification_tf.py, tests/tensorflow/test_models_factory.py
This PR:
- apply suggestions for vit @frgfm 
=> [models] update vit and transformer layer norm

.github/workflows/scripts.yml, scripts/detect_text.py
This PR:
- refactored detection script
- add ability to save also as xml
- add minor test
=> [refactor] detection script

doctr/models/classification/vit/pytorch.py, doctr/models/classification/vit/tensorflow.py, doctr/models/modules/transformer/pytorch.py, doctr/models/modules/transformer/tensorflow.py, doctr/models/modules/vision_transformer/pytorch.py
This PR:
- fix intermediate size scaling before: PFF (MLP) dim always 768 (same as d_model) but base model has a size from 3072 so scale x 4
- unify TF with PT
PT: (@frgfm thanks for torch-scan :+1: )
```
__________________________________________________________________________________________
Layer                        Type                  Output Shape              Param #
==========================================================================================
visiontransformer            VisionTransformer     (-1, 126)                 0
├─0                          PatchEmbedding        (-1, 65, 768)             37,632
├─1                          EncoderBlock          (-1, 65, 768)             85,022,208
├─2                          ClassifierHead …
```
=> [models] Vit: fix intermediate size scale and unify TF to PT

doctr/models/detection/linknet/pytorch.py, doctr/models/detection/zoo.py, doctr/models/recognition/zoo.py, doctr/models/zoo.py
=> make pretrained backbone flexible in predictor

README.md, docs/source/index.rst, docs/source/modules/models.rst, doctr/models/classification/vit/pytorch.py, doctr/models/classification/vit/tensorflow.py, doctr/models/classification/zoo.py, doctr/models/modules/vision_transformer/pytorch.py, doctr/models/modules/vision_transformer/tensorflow.py, doctr/models/recognition/__init__.py, doctr/models/recognition/vitstr/__init__.py, doctr/models/recognition/vitstr/base.py, doctr/models/recognition/vitstr/pytorch.py, doctr/models/recognition/vitstr/tensorflow.py, doctr/models/recognition/zoo.py, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_factory.py, tests/pytorch/test_models_recognition_pt.py, tests/tensorflow/test_models_classification_tf.py, tests/tensorflow/test_models_factory.py, tests/tensorflow/test_models_recognition_tf.py
This PR:
- adds ViTSTR in TF and PT
- update ViT config
- add pos_interpolation to ViT to make it work also on higher image resolutions (case: recognition) as backbone
- ViT tf refactor patchify to reduce memory consuption (now it is similar to PT implementation TF: vit_s: 8.9 GB to PT: 7.5GB)
(This difference is normal faiced the same % diff in SAR and MASTER between TF and PT)
- apply some fixes
- added model configs in this PR in both frameworks are: vit_s, vit_b (updated), viststr_small, vitstr_base 
Any feedback is very welcome :hugs: 
NOTE: 
Unlike the SAR or MASTER architecture, I am not able to fully train the model because ViT requires a lot of data and I cannot muster the computing power. So just a little test this time based on our word generator to show that it trains well. …
=> [models] add ViTSTR TF and PT and update ViT to work as backbone

doctr/models/classification/vit/pytorch.py, doctr/models/classification/vit/tensorflow.py, doctr/models/modules/vision_transformer/pytorch.py, doctr/models/modules/vision_transformer/tensorflow.py, doctr/models/recognition/vitstr/pytorch.py, doctr/models/recognition/vitstr/tensorflow.py, doctr/models/utils/pytorch.py
This PR: 
- make pretrained checkpoints available for ViT (TF and PT)
- rework patchify make it dynamic to the input shape
- rework pretrained backbone usage for ViTSTR with checkpoints
- fix issue with bicubic scale and onnxruntime (use bilinear : minor cost on quality and speed up)
All added checkpoints >98% acc
=> [models] ViT add checkpoints and some rework to use pretrained ViT backbone in ViTSTR

setup.py
This PR:
- update version to 0.6.0a0 for minor release next week
- release tracker will be updated today - done :)
:hugs: 
CI will pass after merge #1072
=> update version for minor release

doctr/models/recognition/vitstr/pytorch.py, doctr/models/recognition/vitstr/tensorflow.py
This PR:
- disable using pretrained backbone in VITSTR by default
- after some tests it runs much better without using the pretrained backbone
=> ViTSTR disable pretrained backbone by default

doctr/models/classification/predictor/pytorch.py
Related to https://github.com/mindee/doctr/pull/1039, closes https://github.com/mindee/doctr/issues/1020
=> fix classification model cuda move

.github/workflows/docker.yml, api/Dockerfile, api/docker-compose.yml, api/pyproject.toml
Fix https://github.com/mindee/doctr/issues/1126
Now, the docker container in `api` folder uses directly DocTR GitHub repository instead of the wheel on PyPI. This is done until `0.7.0` is released.
=> fix: :wrench: docker api use GitHub repository

doctr/datasets/sroie.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
Fixing the unpacking archive of SROIE dataset.
=> Error in unpacking archive of SROIE dataset

docs/build.sh, doctr/version.py, setup.py
This PR:
- remove version.py which is autogenerated
- fix for docs build after #1177 
- lower package identifier to patch and not minor + patch up
=> [Fix] remove autogen version.py fix docs build and fix version identifier

api/pyproject.toml, pyproject.toml, tests/tensorflow/test_models_classification_tf.py
This PR:
- upgrades the minor version of tf2onnx to >=1.14 (which supports TF 2.11)
- upgrades the minor version of tensorflow to >= 2.11 (first version where the issue seems to be fixed)
- enables tests
Closes:
#978 and #790 🚀
=> [tests/TF/build] enable missing classification onnx tests and set tensorflow lower bound to 2.11

pyproject.toml
This PR:
- update torch to  minimum to work also with py3.10 (related to: #1184)
- add onnx which is optional for torch>=2.0.0 but needed for our onnx exports
=> [build] update pytorch dependency

doctr/datasets/cord.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
Fixing the unpacking archive of CORD dataset.
=> [FIX] Error in unpacking archive of CORD dataset

.github/workflows/builds.yml, .github/workflows/demo.yml, .github/workflows/doc-status.yml, .github/workflows/docker.yml, .github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/pr-labels.yml, .github/workflows/pull_requests.yml, .github/workflows/references.yml, .github/workflows/release.yml, .github/workflows/scripts.yml, .github/workflows/style.yml, README.md, docs/source/getting_started/installing.rst, pyproject.toml
This PR:
- drops support for python 3.6 and 3.7 (latest packages mostly have a mimum python version from 3.8 for example pytorch 2.0)
- update CI also to be up to date
Any feedback is welcome :)
=> [build] drop py3.6/3.7 support and update CI default to py3.8/3.9

.github/workflows/main.yml, Makefile, doctr/models/utils/pytorch.py, doctr/models/utils/tensorflow.py, pyproject.toml, tests/pytorch/test_models_recognition_pt.py, tests/tensorflow/test_models_classification_tf.py, tests/tensorflow/test_models_detection_tf.py, tests/tensorflow/test_models_recognition_tf.py
This PR:
- update last missing cache action
- remove fixed opset version which are not more needed after changing the minimum pt / tf version)
- temporarily skip on CI for TF classification onnx export (tf2onnx 1.14 seems to raise a memory leak which kills the CI machine) - locally all tests passes for me, but yeah the tf resnet >= 31 now takes ~16GB RAM while converting 
Not sure if it comes from TF itself or tf2onnx
Maybe setting up a larger runner: @charlesmindee @odulcy-mindee (or we skip more tf onnx tests ..ftm)
https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners
Any feedback is welcome 🤗
=> [CI] change old cache action and skip TF classification onnx export temporarily

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/linknet/pytorch.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/vitstr/tensorflow.py
some minor fixes before the models will be trained
=> [Fix] add missing mean/std defaults, add missing weight init for sar

doctr/models/classification/magc_resnet/tensorflow.py, doctr/models/classification/resnet/pytorch.py, doctr/models/classification/vit/pytorch.py, doctr/models/classification/vit/tensorflow.py
This PR:
- adds new checkpoints for vit_s and vit_b Tensorflow and Pytorch
- new checkpoint for magc_resnet31 Tensorflow
- new checkpoint for resnet34_wide Pytorch
- all models acc >=95%
@odulcy-mindee please upload the checkpoints on your file storage and send me the new urls :)
=> [classification] vit and magc_resnet checkpoints

doctr/models/classification/predictor/pytorch.py, doctr/models/detection/predictor/pytorch.py, doctr/models/detection/zoo.py, doctr/models/recognition/predictor/pytorch.py, doctr/models/recognition/zoo.py, doctr/models/utils/pytorch.py, doctr/models/zoo.py, tests/pytorch/test_models_utils_pt.py
This PR:
- adds precision dtype to predictor / det predictor and reco predictor (effects only PT)
Revert for TF which would need to convert the weights while loading (takes a lot of time) 
tests depends on: #1201 
issue: #1112
=> [Feat] Predictor precision PT backend

doctr/models/recognition/parseq/pytorch.py, doctr/models/recognition/vitstr/pytorch.py
This PR:
- contains fixes for the pytorch version of PARSeq
dummy run:
Validation loss decreased 0.407558 --> 0.322983: saving state...
Epoch 8/20 - Validation loss: 0.322983 (Exact: 82.78% | Partial: 83.81%)
=> [Fix] PARSeq pytorch fixes

doctr/models/recognition/parseq/tensorflow.py
This PR:
- several fixes
torch fail will be fixed if #1227 is merged
Validation set loaded in 0.002758s (2520 samples in 79 batches)
Train set loaded in 0.003837s (126000 samples in 3937 batches)
Validation loss decreased inf --> 4.64792: saving state...                                                                                                      
Epoch 1/20 - Validation loss: 4.64792 (Exact: 0.08% | Partial: 0.08%)
Validation loss decreased 4.64792 --> 4.37974: saving state...                                                                                                  
Epoch 2/20 - Validation loss: 4.37974 (Exact: 0.48% | Partial: 0.91%)
Validation loss decreased 4.37974 --> 4.3734: saving state... …
=> [Fix] PARSeq tensorflow fixes

.github/workflows/main.yml, doctr/file_utils.py, doctr/io/image/tensorflow.py, doctr/models/factory/hub.py, doctr/models/recognition/utils.py, tests/common/test_core.py, tests/common/test_datasets_utils.py, tests/common/test_io.py, tests/common/test_models_recognition_utils.py, tests/pytorch/test_io_image_pt.py, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_detection_pt.py, tests/pytorch/test_models_recognition_pt.py, tests/tensorflow/test_io_image_tf.py, tests/tensorflow/test_models_detection_tf.py, tests/tensorflow/test_models_recognition_tf.py
This PR:
- updates codecov action to latest
- updates / adds some missing tests (there are still some missing ones but this would go beyond the scope of this PR)
- fixes a minor bug in `merge_strings`  -> `doctr/models/recognition/utils.py`
- add some no-cover for `file_utils.py` and `hub.py`  because we cannot test some cases or it is already tested by third party lib (e.g.: hf hub)
=> [tests/bug] improve tests and fix a minor bug

pyproject.toml, references/detection/evaluate_tensorflow.py
This PR:
- fix minor bug in det eval script
- set upper bound for rapidfuzz to avoid lib breaks again
- update hf hub lib to 0.5.0 (to follow with our python < 3.8 non support)
=> [fix/chore] fix bug in tf det eval script / update dep version specifier

doctr/datasets/datasets/base.py
- Small quick fix to make training object detection working again.
=> fix: :bug: fix bug when training object detection

docs/build.sh, doctr/models/classification/vit/tensorflow.py, doctr/transforms/functional/tensorflow.py, doctr/transforms/modules/tensorflow.py, pyproject.toml, tests/tensorflow/test_transforms_tf.py
This PR:
- replaces `tensorflow_addons` which is end of life (May 2024) --> https://github.com/tensorflow/addons/issues/2807
- add hotfix for docs build
- maybe some space for improvements
Any feedback is welcome :)
=> [chore]: Replace `tensorflow_addons` 

.github/workflows/references.yml, references/classification/train_tensorflow.py, references/detection/train_tensorflow.py, references/recognition/train_tensorflow.py, references/requirements.txt
This PR introduces [ClearML](https://clear.ml/pricing/) support in references script, for TensorFlow only (PyTorch will be done in another PR).
At the moment, ClearML captures **everything**, meaning that logs, model checkpoints, etc. are tracked. Do we want to keep it like that or do we want to block everything [auto_connect_frameworks](https://clear.ml/docs/latest/docs/references/sdk/task/#taskinit) in `Task.init` by default ? If so, how do we expose parameters to users to tune this behavior ?
=> feat: :sparkles: ClearML support for TensorFlow

README.md, api/README.md, references/classification/README.md, references/detection/README.md, references/recognition/README.md
This PR:
- Fix markdown style warnings
=> [style] Fix markdown style warnings

docs/source/using_doctr/using_model_export.rst
This PR:
- Updates export page in docs
- Replaces outdated content which does not work (Onnx works for both TF and PT - we decided to support Onnx as format for model export)
- Adds samples for FP16 TF / PT
=> [docs] update export page to ONNX

doctr/models/obj_detection/faster_rcnn/pytorch.py, doctr/transforms/modules/pytorch.py
This PR:
- fix object detection training also with pretrained (change to torchvision's new weights loading -> pretrained is deprecated)
- fix the endless warnings from each torchvision resize operation (warning that `antialias` will change by default to `True` in v0.17)
=> [Fix] fix obj det train and suppress endless warning prints

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/linknet/pytorch.py
This PR:
- make it possible to use `--pretrained` if you use a pretrained det model and train on a KIE dataset
- does nothing change for "normal" det training and inference
- same way we have handled it for recognition on differing vocabs
=> [Fix] add ignore keys if classes differ - KIE training

demo/backend/pytorch.py, demo/backend/tensorflow.py
This PR:
- updates the available models in the demo
- will be full available after #969  and closes #1206
=> [demo] update models list for Tf / PT backend

doctr/models/classification/mobilenet/pytorch.py, doctr/models/classification/resnet/pytorch.py, doctr/models/classification/vgg/pytorch.py, doctr/models/detection/differentiable_binarization/pytorch.py
This PR:
- same as done for object detection update to new torchvision API
=> [chore] update to new torchvision API in models as well

api/pyproject.toml, pyproject.toml
This PR:
- updates API dependencies
- remove upper bounds for dev dependencies
- increase minimum tf2onnx version to fix the incompatibility with >tf2.12
=> [chore]: clean dependencies

doctr/models/preprocessor/pytorch.py
This PR:
- fix inconsistency of antialising in PreProcessor
=> [FIX] antialising in PreProcessor

references/detection/train_pytorch.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py
This PR:
- update pytorch DDP script also with newly added augmentations
- add backbone freezing also for recognition scripts
=> [scripts] Add backbone freeze for recognition scripts and update augmentations also for DDP script

doctr/models/recognition/parseq/pytorch.py, doctr/models/recognition/parseq/tensorflow.py, doctr/models/recognition/vitstr/pytorch.py, doctr/models/recognition/vitstr/tensorflow.py
This PR:
- fix prob comp for vitstr and parseq models
=> [Fix] prob computation for parseq and vitstr models

doctr/models/classification/predictor/pytorch.py, doctr/models/detection/predictor/pytorch.py, doctr/models/kie_predictor/pytorch.py, doctr/models/predictor/pytorch.py, doctr/models/recognition/predictor/pytorch.py, references/classification/latency_pytorch.py, references/detection/evaluate_pytorch.py, references/detection/latency_pytorch.py, references/obj_detection/latency_pytorch.py, references/recognition/evaluate_pytorch.py, references/recognition/latency_pytorch.py, scripts/detect_artefacts.py
This PR:
- change from `no_grad` to `inference_mode`  (ref.: https://pytorch.org/docs/stable/generated/torch.inference_mode.html)
- ref: #1316 
```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
import time
doc_path = "/home/felix/Desktop/1.jpg"
start = time.time()
doc = DocumentFile.from_images([doc_path] * 10)
model = ocr_predictor(det_arch="db_resnet50", reco_arch="parseq", pretrained=True, det_bs=8, reco_bs=512).cuda().half()
result = model(doc)
print(time.time() - start)
```
```
```
=> [PyTorch] replace no_grad with inference_mode

doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/linknet/pytorch.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/parseq/pytorch.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/vitstr/pytorch.py, doctr/models/utils/pytorch.py, tests/pytorch/test_models_utils_pt.py
`.numpy()` in PyTorch only supports limited scalar types: [aten_to_numpy_dtype](https://github.com/pytorch/pytorch/blob/de3ae93e9b7dd522a74e0f5fd33fc5eeed8836cc/torch/csrc/utils/tensor_numpy.cpp#L274-L301).
When running BF16 with autocast, an error will be thrown here when calling `.numpy()`: `TypeError: Got unsupported ScalarType BFloat16`.
Convert BF16 tensor to float before calling `.numpy()` to fix this error.
=> [Fix] PT - convert BF16 tensor to float before calling .numpy()

doctr/models/recognition/parseq/pytorch.py, doctr/models/recognition/parseq/tensorflow.py, doctr/models/recognition/vitstr/pytorch.py, doctr/models/recognition/vitstr/tensorflow.py
This PR:
- Add `0.0` in prob comp if word is empty
=> [Fix] Prob comp in vitstr and parseq for empty words

doctr/models/detection/differentiable_binarization/tensorflow.py, doctr/models/detection/linknet/tensorflow.py, doctr/models/modules/transformer/pytorch.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/crnn/tensorflow.py, doctr/models/recognition/master/tensorflow.py, doctr/models/recognition/parseq/tensorflow.py, doctr/models/recognition/sar/tensorflow.py, doctr/models/recognition/vitstr/tensorflow.py, doctr/models/utils/pytorch.py, doctr/models/utils/tensorflow.py, tests/pytorch/test_models_utils_pt.py, tests/tensorflow/test_models_utils_tf.py
replace #1344 
@odulcy-mindee you can check this later if you have a bit more time ^^
=> [Fix] TF - add bf16 numpy dtype conversion

doctr/models/recognition/crnn/pytorch.py
This PR:
- fix growing mem usage
- training still works
=> [Fix] fix growing mem usage pytorch crnn

references/detection/train_tensorflow.py, references/recognition/train_tensorflow.py
This PR:
- fix `ToGray` output channels issue
- unify recognition augs from pt and tf (except RandomPerspective)
=> [Fix]  tf augmentations

pyproject.toml, setup.py
This PR:
- increase version to 0.8.0 (docker feature / orientation improvement / etc. -> minor instead of patch)
- temp pin onnx until https://github.com/onnx/tensorflow-onnx/pull/2252 is fixed
=> [misc] increase to 0.8.0 and temp pin onnx

README.md
Currently links to https://weasyprint.readthedocs.io/ which says:
https://weasyprint.org looks to be a better URL.
=> Fix broken weasyprint link

README.md, doctr/io/elements.py, doctr/models/_utils.py, doctr/models/builder.py, doctr/models/detection/predictor/pytorch.py, doctr/models/detection/predictor/tensorflow.py, doctr/models/kie_predictor/pytorch.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/models/zoo.py, scripts/analyze.py, tests/common/test_io_elements.py, tests/common/test_models.py, tests/common/test_models_builder.py, tests/pytorch/test_models_detection_pt.py, tests/pytorch/test_models_zoo_pt.py, tests/tensorflow/test_models_detection_tf.py, tests/tensorflow/test_models_zoo_tf.py
This PR:
- update page orientation detection (Now we calculate the orientation on the segmentation mask - much more robust - and will be more robust until all detection models are trained with rotation augmented samples)
- update builder (now each page element contains the processed page image - easier for the user if they work with rotated documents for example to grab the orientation corrected page)
- soft breaking change: now we can use the processed image directly for visualization - straightened pages are now also correctly displayed 
Any feedback is super welcome :hugs: 
open todos:
=> [prototype] compute orientation on segmentation map

doctr/models/preprocessor/tensorflow.py, doctr/transforms/modules/tensorflow.py, tests/tensorflow/test_models_preprocessor_tf.py, tests/tensorflow/test_transforms_tf.py
This PR: 
- changes `antialias` also for TF to True
NOTE tests:
- super minimal difference (< 1e-6) in the expected output  (e.g.: 5.00001 instead of 5.0  /  1.00002 instead of 1.0) - 
I don't think there's much we can do about that (the results are correct and close to PT see below)
=> TF change antialias to true

pyproject.toml, references/classification/train_pytorch.py, references/classification/train_tensorflow.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/obj_detection/train_pytorch.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py, references/requirements.txt
I have not been able to run `train_pytorch.py` script on Colab. An idea is to use `tqdm` instead of `fastprogress`.
Related to https://github.com/mindee/doctr/discussions/1388 and https://github.com/mindee/doctr/discussions/1106
=> feat: :sparkles: use `tqdm` instead of `fastprogress` in reference scripts

references/classification/train_pytorch.py, references/classification/train_tensorflow.py, references/classification/utils.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/detection/utils.py, references/obj_detection/train_pytorch.py, references/obj_detection/utils.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py, references/recognition/utils.py
=> Added early stopping feature

Dockerfile
Add `libsqlite3-dev` so `sqlite3` can work properly on `python`. Useful for other packages such as `dvc[s3]`.
=> fix: :bug: add sqlite dependency

doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/differentiable_binarization/tensorflow.py, doctr/models/detection/linknet/base.py, doctr/models/detection/linknet/tensorflow.py
This PR:
- change DB loss from Balanced BCE to Focal loss
- fix target building
=> [FIX] db loss TF and PT also for training with rotated samples

.github/workflows/references.yml, doctr/datasets/__init__.py, doctr/datasets/orientation.py, doctr/datasets/rotation.py, doctr/models/detection/differentiable_binarization/pytorch.py, doctr/transforms/functional/tensorflow.py, references/classification/README.md, references/classification/train_pytorch_orientation.py, references/classification/train_tensorflow_orientation.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
This PR:
- Add training scripts (TF & PT) for the crop orientation classifier and additional for general document orientation classification (needed for 0.9.0 (similar to the crop_orientation_predictor) to generally recognize the documents rotation angle correctly before we compute the angle from the bin_map - which works only for rotated documents in the range ~ -60-60 well)
- Add a simple dataset (prefilled with 0 degree targets - to match the AbstractDataset checks)
Any feedback is welcome :)
Dummy runs (mobilenet_v3_small)
```
crop orientation (800k train / 200k val)
Validation loss decreased 0.372947 --> 0.355291: saving state...
Epoch 5/30 - Validation loss: 0.355291 (Acc: 81.51%)
doc orientation (only 4k train / 1k val)
Validation loss decreased 0.559973 --> 0.481535: saving …
```
=> [references] TF / PT crop & document orientation classifier train scripts

doctr/models/classification/textnet/pytorch.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py
This PR:
- remove useless submodule to make it easier to extract the required midlevel features
- lower some probs in det augmentations
=> [PT] remove submodule from textnet arch

demo/app.py
This PR:
- fix for demo with latest streamlit version
=> [FIX] Fix streamlit demo

doctr/models/detection/differentiable_binarization/pytorch.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py
This PR:
- Add Polynomial Scheduler for detection training (TF & PT)
- It's often mentioned in text detection papers like DB & FAST & .. so i think it is a good idea to add it :)
=> [references] Add poly scheduler for detection training

references/detection/train_pytorch.py, references/detection/train_tensorflow.py
This PR:
- Add the option to save after each epoch (@odulcy-mindee as we saw this would be a very useful option ^^)
=> [references] Add interval saving for detection trainings

doctr/utils/geometry.py, tests/common/test_utils_geometry.py
This PR:
- raise instead of runtime warning and catch to handle explicit zero division and invalid value encountered (NaN)
=> [Fix] Catch Divide by zero explicit

doctr/datasets/recognition.py, doctr/datasets/utils.py, references/recognition/README.md
fixes issues raised in https://github.com/mindee/doctr/discussions/1366 where vocab issues arrise if labels.json file is not processed in correct encoding
=> read labels in utf-8 and log input string on vocab error

docs/source/using_doctr/using_models.rst
This PR:
- add documentation with DocumentBuilder options
- add missing render export 
=> [Docs] extend doc with DocumentBuilder options

doctr/models/classification/textnet/pytorch.py, doctr/models/classification/textnet/tensorflow.py, doctr/models/detection/fast/base.py, doctr/models/detection/fast/pytorch.py, doctr/models/detection/fast/tensorflow.py, doctr/models/modules/layers/pytorch.py, doctr/models/modules/layers/tensorflow.py, tests/pytorch/test_models_detection_pt.py, tests/tensorflow/test_models_detection_tf.py
This PR:
- Fix mistake in FASTConvLayer (special thanks to @czczup (FAST author) for finding this mistake)
- Fix tensorflow reparameterization
- Provide new pretrained backbone checkpoints
- Add small test to check that reparam works as expected
@odulcy-mindee Please upload the checkpoints before :)
=> [FIX] Fix mistake in FASTConvLayer and tf reparameterization

.conda/meta.yaml, doctr/utils/metrics.py, doctr/utils/visualization.py, pyproject.toml, tests/common/test_utils_metrics.py
This PR addresses "Unidecode has a problematic OSS license #1508".
=> Replace unidecode with text-unidecode.

api/README.md, api/app/routes/kie.py, api/app/routes/ocr.py, api/app/schemas.py, api/tests/conftest.py, api/tests/routes/test_kie.py, api/tests/routes/test_ocr.py, docs/source/using_doctr/using_models.rst, doctr/io/elements.py, doctr/models/builder.py, doctr/models/classification/predictor/pytorch.py, doctr/models/classification/predictor/tensorflow.py, doctr/models/kie_predictor/pytorch.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, tests/common/test_io_elements.py, tests/common/test_models_builder.py, tests/pytorch/test_models_classification_pt.py, tests/tensorflow/test_models_classification_tf.py
This PR:
- Add result from crop orientation classifier to the output (so users are able to work with the general word orientation)
Note: feature request from: @mllife
=> [feature] Add word crop general orientation to output

docs/source/modules/models.rst, doctr/models/classification/mobilenet/pytorch.py, doctr/models/classification/mobilenet/tensorflow.py, doctr/models/classification/predictor/pytorch.py, doctr/models/classification/predictor/tensorflow.py, doctr/models/classification/zoo.py, doctr/models/kie_predictor/base.py, doctr/models/predictor/base.py, references/classification/train_pytorch_orientation.py, references/classification/train_tensorflow_orientation.py, tests/pytorch/test_models_classification_pt.py, tests/tensorflow/test_models_classification_tf.py
This PR:
- Allign orientation train scripts to current model behavior (counter clockwise instead of clockwise - fix labels)
- change to general OrientationPredictor (for crop and page orientation models)
=> [Fix] allign orientation train script to current orientation model (counter clockwise instead of clockwise) & make OrientationPredictor dynamic

doctr/utils/metrics.py, references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/requirements.txt, scripts/evaluate.py, scripts/evaluate_kie.py, tests/common/test_utils_metrics.py
This PR:
- boost polygon iou (from hours to a few minutes) and try to keep an balanced memory consumption
- remove now unused functions in `metrics.py`
- remove unused `use_broadcasting` / `mask_shape` and `psutil` requirements for references
- memory usage tested with oversampled funsd validation dataset (~4K samples) tooks around 6.5 GB RAM
Closes: #1472
=> [metrics] speed up polygon iou (for --rotation) by keeping balanced memory footprint

references/classification/train_pytorch_orientation.py, references/classification/train_tensorflow_orientation.py
This PR:
- augment randomly the angle while training (+-25 degree) (expand if not directly 0, 90, 180 or -90)
- the idea: the current orientation models works pretty well if the real angle of the page or crop is close to [0, 90, 180, -90] but has some lack with larger deviations like >+- 5 degree
@odulcy-mindee We should test it on the TF orientation model training runs i think this will improve the robustness a lot and then do the same again with the PT models (or we test it directly with the PT models)
=> [orientation] augment angle while training

.github/workflows/main.yml, Makefile, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_detection_pt.py, tests/pytorch/test_models_recognition_pt.py, tests/tensorflow/test_models_classification_tf.py, tests/tensorflow/test_models_detection_tf.py, tests/tensorflow/test_models_recognition_tf.py
This PR:
- extend the test with missing allclose check for onnx export - non critical - only warn
- rs will output also why tests was skipped (only as information for us)
=> [tests/onnx] Add onnx and model out check

docs/source/modules/transforms.rst, doctr/transforms/modules/pytorch.py, doctr/transforms/modules/tensorflow.py, tests/pytorch/test_transforms_pt.py, tests/tensorflow/test_transforms_tf.py
This PR:
- Add RandomResize (like ZoomOut)
- Adding to pipeline in a seperate PR
with rot:
without:
=> [transforms] Add RandomResize (like ZoomOut)

doctr/transforms/modules/base.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, tests/common/test_transforms.py
This PR:
- Update det augmentations (more cleaner split now: general | handy/bad copy | diff light etc. | None) 
- Extend OneOf that it can also be used for sample augmentations
- Fix a small issue in RandomCrop 
Tested on a (22K train / 4k val) hf PDFA dataset subset with an general improve of ~ +4% recall +6% precision +3% iou (only as an initial state we need to see how it works on your dataset)
=> [references] Update detection augmentations

doctr/transforms/modules/pytorch.py, doctr/transforms/modules/tensorflow.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, tests/pytorch/test_transforms_pt.py, tests/tensorflow/test_transforms_tf.py
This PR:
- choose preserve aspect ratio and symmetric_pad also randomly to cover more cases
=> [transforms] small random resize improvement

demo/backend/pytorch.py, demo/backend/tensorflow.py, doctr/models/detection/zoo.py, doctr/models/zoo.py, scripts/analyze.py, scripts/detect_text.py, tests/pytorch/test_models_zoo_pt.py, tests/tensorflow/test_models_zoo_tf.py
This PR:
- changes the default detection model from `db_resnet50` to `fast_base`
- reason: 
- more accure (actually much much better also on rotated samples) / needs less memory / small bit faster 
NOTE: marked as breaking change because with the next release we should mention this change and to revert to the previous behavior that it only requires to pass `db_resnet50` as det_arch
=> [models] Change default model to `fast_base` - soft breaking change

doctr/datasets/utils.py, doctr/io/image/pytorch.py
The previous behavior opened PIL images, but didn't release their memory, causing a huge memory leak on our training pipeline.
With this PR, the PIL images will be closed immediately after the copy as numpy array or torch tensor is created.
=> [Fix] close PIL images when loading images to tensor/numpy

docs/source/using_doctr/using_model_export.rst
This PR:
- Update doc section how to do inference with onnx exported models
Closes: #984
=> [docs] Add onnx inference doc

api/README.md, api/app/routes/detection.py, api/app/routes/kie.py, api/app/routes/ocr.py, api/app/schemas.py, api/tests/conftest.py, api/tests/routes/test_kie.py, api/tests/routes/test_ocr.py, docs/source/using_doctr/using_models.rst, doctr/io/elements.py, doctr/models/builder.py, doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/fast/base.py, doctr/models/detection/linknet/base.py, doctr/models/kie_predictor/pytorch.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/utils/geometry.py, tests/common/test_io_elements.py, tests/common/test_models_builder.py, tests/common/test_models_detection.py, tests/common/test_utils_geometry.py
This PR:
- unify detection predictor output (N, 5) / (N, 5, 2)  --> last is objectness_score
- add objectness score to Document output
- update API template
- update docs
- add corresponding tests
Use case: enables the end user to filter out some detected artefacts for example
NOTE: API tests will fail until merged :)
Related to: #1612
=> [builder] Add objectness scores

references/detection/train_pytorch.py, references/detection/train_tensorflow.py
This PR:
- small fix for training with rotations and eval on straight
- ignore scores from results
=> [bug] exclude scores if rot and eval straight

doctr/models/_utils.py, doctr/models/classification/mobilenet/pytorch.py, doctr/models/classification/mobilenet/tensorflow.py, doctr/models/kie_predictor/base.py, doctr/models/kie_predictor/pytorch.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, tests/common/test_models.py, tests/pytorch/test_models_zoo_pt.py, tests/tensorflow/test_models_zoo_tf.py
This PR:
- refactor `OCRPredictor` logic (limit duplication)
- extend estimate angle function to handle also upside-down images
- correct return value from estimate angle (negative - left side rot / positive - right side rot) -> update tests
- integrate `page_orientation_predictor` 
NOTE: Draft until TF orientation models are merged
Closes: #1460
=> [orientation] page orientation improvements

doctr/models/detection/zoo.py
When loading a custom model using `ocr_predictor` with `assume_straight_pages = False`, the preprocessor will be initialized with `assume_straight_pages = True`, resulting in a crash. This behavior happens in any custom detection models.
Example with the default db_resnet50:
```python
from doctr.models import ocr_predictor, db_resnet50
from torch import load
from cv2 import imread
det_arch = db_resnet50(pretrained=False, pretrained_backbone=False)
params = load("db_resnet50-79bd7d70.pt", map_location="cpu")
det_arch.load_state_dict(params)
reader = ocr_predictor(det_arch=det_arch, assume_straight_pages=False)
img = imread("<img>")
print(
reader([img])
)  # => IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```
=> Fixed assume_straight_pages for custom models

doctr/models/builder.py, doctr/models/kie_predictor/pytorch.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/modules/vision_transformer/pytorch.py, doctr/models/modules/vision_transformer/tensorflow.py, doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py
This PR:
- fix rotate condition for straighten pages
- fix new shapes after straightening pages
- ruff recommendations
=> [Bug] fix straighten pages 

api/app/schemas.py, demo/app.py, demo/backend/pytorch.py, demo/backend/tensorflow.py, docs/source/using_doctr/using_models.rst, doctr/models/classification/predictor/pytorch.py, doctr/models/classification/predictor/tensorflow.py, doctr/models/classification/zoo.py, doctr/models/kie_predictor/base.py, doctr/models/kie_predictor/pytorch.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/predictor/base.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/utils/geometry.py, tests/common/test_utils_geometry.py, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_zoo_pt.py, tests/tensorflow/test_models_classification_tf.py, tests/tensorflow/test_models_zoo_tf.py
Hi @felixdittrich92 ,
I've merged your changes from disable orient prototype and slightly modified the function extract_rcrops which works better according to some of my internal tests.
=> Disable page and crop orientation

Makefile, docs/source/using_doctr/using_datasets.rst, doctr/datasets/cord.py, doctr/datasets/datasets/base.py, doctr/datasets/funsd.py, doctr/datasets/ic03.py, doctr/datasets/ic13.py, doctr/datasets/iiit5k.py, doctr/datasets/imgur5k.py, doctr/datasets/sroie.py, doctr/datasets/svhn.py, doctr/datasets/svt.py, doctr/datasets/synthtext.py, doctr/datasets/utils.py, doctr/datasets/wildreceipt.py, references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
This PR:
- makes it possible to use built-in datasets also to plug in the detection training script
- extend tests
- update eval scripts - no it works with different args out of the box
=> [datasets] Allow detection task for built-in datasets

api/app/vision.py, doctr/transforms/modules/pytorch.py, doctr/transforms/modules/tensorflow.py, references/classification/latency_tensorflow.py, references/classification/train_tensorflow_character.py, references/classification/train_tensorflow_orientation.py, references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, references/detection/latency_tensorflow.py, references/detection/train_tensorflow.py, references/recognition/evaluate_tensorflow.py, references/recognition/latency_tensorflow.py, references/recognition/train_tensorflow.py, scripts/analyze.py, scripts/detect_text.py, scripts/evaluate.py, scripts/evaluate_kie.py, tests/pytorch/test_transforms_pt.py, tests/tensorflow/test_transforms_tf.py
This PR:
- fix for eval scripts with keeping aspect ratio / symmetric pad - optional
- tf: fix deprecated 
- fix small overflow
=> [Bug] Fix eval scripts + possible overflow in Resize

.conda/meta.yaml, README.md, docs/source/getting_started/installing.rst, pyproject.toml, setup.py
This PR:
- change to 0.10 for next release (already a lot of minor stuff added since 0.9.0 so next is not a patch release)
- I think it's time to move to pytorch >= 2.0 (already close before 2.5) ^^
Any feeback is welcome :hugs: 
PS: Afterwards i would update all related issues / tracker / etc.
PSS: labeled as breaking change that we don't miss to mention in the next release notes :)
=> [Build] update minor version & update torch to >= 2.0

doctr/io/elements.py, doctr/utils/reconstitution.py, tests/common/test_utils_reconstitution.py
This PR:
- Improve synthesize quality
- Allow also to render polygons but warn because to large rotations can't be rendered correctly yet
- Extend corresponding tests
Still not perfect but looks much better as before :)
Old:  (Lots of overlapping / clipping)
New:
New without line:
=> [Reconstitution] Improve reconstitution

.pre-commit-config.yaml, doctr/datasets/datasets/pytorch.py, doctr/datasets/datasets/tensorflow.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/transforms/functional/tensorflow.py, doctr/utils/data.py, doctr/utils/metrics.py, references/classification/train_pytorch_character.py, references/classification/train_pytorch_orientation.py, references/classification/train_tensorflow_character.py, references/classification/train_tensorflow_orientation.py, references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, references/recognition/evaluate_pytorch.py, references/recognition/evaluate_tensorflow.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py, tests/pytorch/test_transforms_pt.py, tests/tensorflow/test_transforms_tf.py
This PR:
- Fix failing TF test
- Formatting
=> [tests/style] Fix tf test and formatting

doctr/file_utils.py, doctr/models/recognition/parseq/tensorflow.py, doctr/models/utils/tensorflow.py
This PR:
- move eager mode to the only required part -> exporting to onnx
- boosts inference + training by ~10%
=> [TF] Change eager mode

CONTRIBUTING.md, doctr/models/classification/zoo.py, doctr/models/detection/zoo.py, doctr/models/preprocessor/pytorch.py, doctr/models/preprocessor/tensorflow.py, doctr/models/recognition/zoo.py
Closes https://github.com/mindee/doctr/issues/1764 -- more details in that issue. Hope this all helps!
=> [models] Change Resize kwargs to args for each zoo predictor

.conda/meta.yaml, .github/workflows/builds.yml, .github/workflows/demo.yml, .github/workflows/doc-status.yml, .github/workflows/docker.yml, .github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/public_docker_images.yml, .github/workflows/publish.yml, .github/workflows/pull_requests.yml, .github/workflows/references.yml, .github/workflows/scripts.yml, .github/workflows/style.yml, README.md, api/Dockerfile, api/pyproject.toml, docs/source/getting_started/installing.rst, doctr/models/_utils.py, doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/fast/base.py, doctr/models/detection/linknet/base.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/predictor/tensorflow.py, doctr/utils/geometry.py, pyproject.toml, references/detection/utils.py
This PR:
- Move to minimum py 3.10 for next release
- reason: 
- numpy 2.0 requires py >= 3.10 
- same for TF >=2.18 because it depends on numpy >= 2.0 
- same for onnxruntime >= 1.19 which dropped support for py 3.9 because of dep  numpy >= 2.0
- Fix mypy
- minor numpy 2.0 compatibility fix int0 -> intp (does also exist in <2.0)
=> [build] Upgrade py 3.10

.github/workflows/clear_caches.yml, .github/workflows/style.yml, doctr/datasets/datasets/pytorch.py, doctr/io/image/pytorch.py, doctr/models/classification/predictor/pytorch.py, doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/predictor/pytorch.py, doctr/models/kie_predictor/pytorch.py, doctr/models/modules/layers/pytorch.py, doctr/models/modules/transformer/pytorch.py, doctr/models/predictor/pytorch.py, doctr/models/preprocessor/pytorch.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/parseq/pytorch.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/vitstr/pytorch.py, doctr/models/utils/pytorch.py, doctr/transforms/functional/pytorch.py, doctr/transforms/modules/pytorch.py
This PR:
- Add a small CI job to clear github runner caches which are older than 2 days
- Fix mypy issues
=> [CI/code quality] Add clear github runner caches job + mypy fixes

.github/workflows/docs.yml, .github/workflows/pr-labels.yml
This PR:
- Fix PR labeler
- Rollback docs deploy deps
=> [CI] Fix PR labeler job & Rollback doc deploy deps

references/detection/README.md, references/detection/train_pytorch_DDP.py
in this script i have implemented the DDP training for detection task.
=> adding pytorch DDP  script of detection task

docs/source/using_doctr/using_models.rst
fix faulty code for prediction and recognition demos
=> docs: fix faulty code for prediction and recognition demos

pyproject.toml
This PR:
- the extra "[and-cuda]" is only available on linux
- for windows only WSL2 (linux) supports direct GPU support - where our logic would match - for native windows the extra does not exist same for MacOS
ref.: https://www.tensorflow.org/install/pip#windows-native
=> [build] Fix tensorflow build dep

.pre-commit-config.yaml, docs/source/using_doctr/using_model_export.rst, docs/source/using_doctr/using_models.rst, doctr/models/classification/zoo.py, doctr/models/detection/differentiable_binarization/pytorch.py, doctr/models/detection/fast/pytorch.py, doctr/models/detection/linknet/pytorch.py, doctr/models/detection/zoo.py, doctr/models/recognition/crnn/pytorch.py, doctr/models/recognition/master/pytorch.py, doctr/models/recognition/parseq/pytorch.py, doctr/models/recognition/sar/pytorch.py, doctr/models/recognition/utils.py, doctr/models/recognition/vitstr/pytorch.py, doctr/models/recognition/zoo.py, doctr/models/utils/pytorch.py, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_detection_pt.py, tests/pytorch/test_models_recognition_pt.py, tests/pytorch/test_models_zoo_pt.py
This PR:
- Add `torch.compile` basic support (different backends / fullgraph is up to the user - we support only the basic compile compatibility with `inductor` (default) backend)
- Add corresponding tests and a documentation section
- No benchmarks added here because this scales with the users hardware
Closes: #1684 #1690
=> [Feat] Add torch.compile support

.pre-commit-config.yaml, doctr/transforms/functional/pytorch.py, doctr/transforms/modules/pytorch.py, references/detection/train_pytorch.py, references/detection/train_tensorflow.py, tests/pytorch/test_transforms_pt.py
This PR:
- Replace mem leaking `GaussianBlur` augmentation and the functional used `F.gaussian_blur` with scipy
- Add corresponding test for own `GaussianBlur` implementation
- Adjust sigma range
=> [Bug] Replace mem leaking torch gaussian_blur in augmentations

references/classification/train_pytorch_character.py, references/classification/train_pytorch_orientation.py, references/classification/train_tensorflow_character.py, references/classification/train_tensorflow_orientation.py, references/detection/train_pytorch.py, references/detection/train_pytorch_ddp.py, references/detection/train_tensorflow.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py, tests/pytorch/test_transforms_pt.py
This PR:
- Unify sched and optim config between train scripts
- Add AdamW as option
=> [references] Unify sched + optim config and add AdamW as option

.github/workflows/builds.yml, .github/workflows/publish.yml
This PR:
- Update conda the new default archive is `.conda` ref.: https://github.com/conda/conda-build/releases/tag/25.1.0
- Replace deprecated `set_output` ref.: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> [CI/CD] Replace deprecated parts conda & publish

references/classification/train_pytorch_character.py, references/classification/train_pytorch_orientation.py, references/classification/train_tensorflow_character.py, references/classification/train_tensorflow_orientation.py, references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, references/detection/train_pytorch.py, references/detection/train_pytorch_ddp.py, references/detection/train_tensorflow.py, references/recognition/evaluate_pytorch.py, references/recognition/evaluate_tensorflow.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py
This PR:
- Small logging updates
- Log train loss and lr also for each epoch
- Progress bar show step val loss
- Progress bar show lr changes on each step
- Instead of print use tqdm to write / comes together with the tqdm logging
=> [references] Update Logging

.pre-commit-config.yaml, references/classification/train_pytorch_character.py, references/classification/train_pytorch_orientation.py, references/classification/train_tensorflow_character.py, references/classification/train_tensorflow_orientation.py, references/detection/evaluate_pytorch.py, references/detection/evaluate_tensorflow.py, references/detection/train_pytorch.py, references/detection/train_pytorch_ddp.py, references/detection/train_tensorflow.py, references/recognition/evaluate_pytorch.py, references/recognition/evaluate_tensorflow.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py
This PR:
- monkeypatch `tqdm.write` if Slack logging is set to send messages directly to the Slack channel
- pbar needs to be "enabled" with Slack logging otherwise it can be disabled
=> [Fix] Fix tqdm slack message write : monkeypatch

doctr/datasets/wildreceipt.py, tests/pytorch/test_datasets_pt.py, tests/tensorflow/test_datasets_tf.py
Hey :)
Thanks for the great repo.
While playing around with docTR and the Wildreceipt dataset I may have discovered a small bug.
When I print the labels in the targets for the second image, I also get the labels for the first image.
**Code to recreate bug:**
```
from doctr.datasets import WILDRECEIPT
test_set = WILDRECEIPT(train=False, img_folder=path_to_data + "/", label_path=path_to_data + "/test.txt")
img, target = test_set[1]
print(target["labels"])
```
**Result:**
`['CHOEUN', 'KOREANRESTAURANT', '2621ORANGETHORPEAVE,FULLERTON.', '(714)879-3574', 'THANKYOU!!', 'DATE', '12/30/2016FRI', '19:19', 'BIBIM.OCTOPUT1', 'S-FOODP.CAKT1', 'PORKDUMPLINT1', 'LABEEFRIBT1', '$13.99', '$14.99', '$8.99', '￥17.99', '4.00xITEMS', 'SUBTOTAL', 'TAX1', 'TOTAL', '$55.96', '$4.48', '$60.44','', '', 'TIME', …
=> [Fix] Fix loading targets in WILDRECEIPT init

.pre-commit-config.yaml, doctr/models/_utils.py, doctr/models/kie_predictor/pytorch.py, doctr/models/kie_predictor/tensorflow.py, doctr/models/predictor/pytorch.py, doctr/models/predictor/tensorflow.py, doctr/utils/geometry.py, tests/tensorflow/test_models_classification_tf.py, tests/tensorflow/test_models_detection_tf.py, tests/tensorflow/test_models_recognition_tf.py
This PR:
- Apply mypy latest version fixes & upgrade pre-commit
- Wrap the TensorFlow export test into xfail to avoid our CI to fail here 
Additional information:
Unfortunately tf2onnx is not well maintained - so I don't expect a quick fix (patch release) here in the next 2-3 months - pinning any deps because of this one failing TF model export / load is not an option
=> [misc] Avoid tf onnx test to fail the CI & mypy fixes

doctr/__init__.py, doctr/datasets/cord.py, doctr/datasets/funsd.py, doctr/datasets/ic03.py, doctr/datasets/ic13.py, doctr/datasets/iiit5k.py, doctr/datasets/imgur5k.py, doctr/datasets/svhn.py, doctr/datasets/svt.py, doctr/datasets/synthtext.py, doctr/datasets/utils.py, references/recognition/train_pytorch.py, references/recognition/train_pytorch_ddp.py, references/recognition/train_tensorflow.py
hey @felixdittrich92,
now we are able to use the builtin dataset, and it is working fine.
=> [references] Recognition - Allow built-in datasets usage

README.md, demo/backend/pytorch.py, docs/source/index.rst, docs/source/modules/models.rst, docs/source/using_doctr/using_models.rst, doctr/models/classification/__init__.py, doctr/models/classification/vip/__init__.py, doctr/models/classification/vip/layers/__init__.py, doctr/models/classification/vip/layers/pytorch.py, doctr/models/classification/vip/pytorch.py, doctr/models/classification/zoo.py, doctr/models/modules/layers/pytorch.py, doctr/models/recognition/__init__.py, doctr/models/recognition/viptr/__init__.py, doctr/models/recognition/viptr/pytorch.py, doctr/models/recognition/zoo.py, tests/pytorch/test_models_classification_pt.py, tests/pytorch/test_models_factory.py, tests/pytorch/test_models_recognition_pt.py
The code has been tested by running training+evaluation for 8 epochs on a single gpu using an 800k multilingual  dataset for training and a 200k multilingual dataset for evaluation. While training loss decreased during training, I didn't observe any substantial increase in precision on the eval dataset. I'm not sure if that's the expected behavior, but in any case I didn't find any errors that would cause that. Let me know if there's something I missed 🙂
=> [Feat] PyTorch - VIP backbone and VIPTR recognition module

doctr/models/detection/differentiable_binarization/base.py, doctr/models/detection/fast/base.py, doctr/models/detection/linknet/base.py
I've recently had the occasion to profile doctr under the following conditions:
* PyTorch with CUDA support
* Models: db_resnet50 & crnn_mobilenet_v3_large
* Approximately 100 png pages at DPI 144, all like:
```
image0199.png PNG 1225x1592 1225x1592+0+0 8-bit Grayscale Gray 256c 623356B 0.000u 0:00.000
```
I performed this profiling using the following command:
```
python scripts/detect_text.py \
--detection db_resnet50 \
--recognition crnn_mobilenet_v3_large \
--profile \
--gpu \
-f txt \
~/ocr-test-data-small
```
This uses the `--profile` feature added by [my other PR `lachesis/speedup`](https://github.com/mindee/doctr/pull/1921).
When running this profiling against the main branch, there was one particular hot-spot that stood out to me: `DBPostProcessor.bitmap_to_boxes`.
Here's the …
=> Use OpenCV instead of Shapely to compute area & length

docs/source/modules/datasets.rst, doctr/datasets/vocabs.py
I have two questions:
1. How do you want to handle languages that use a dual writing system (e.g., Serbian)? Do you want to be able to address them individually so they can be blacklisted/whitelisted or just put them in the same bucket?
2. Can I contribute wordlists? I don't know how you're generating them at the moment.
=> [datasets] feat: add croatian vocabulary

.pre-commit-config.yaml, demo/backend/pytorch.py, docs/source/modules/models.rst, docs/source/using_doctr/using_models.rst, doctr/models/recognition/viptr/pytorch.py, doctr/models/recognition/zoo.py, references/recognition/train_pytorch.py, tests/pytorch/test_models_factory.py, tests/pytorch/test_models_recognition_pt.py
This PR:
- Drop viptr base config
Explanation:
We drop the base config because after some experiments the arch with it's base config doesn't learns well / needs tons of more data (10M +++)
After a param (config) grid search the official tiny config is close the best fit
=> [models] Drop viptr base config

doctr/models/classification/vip/layers/pytorch.py
This PR:
- Fix any issue which lead before to numerical incorrectness after exporting the model to Onnx
=> [bug] Fix viptr onnx export issue

doctr/models/_utils.py
=> [Fix] Correct condition for image dilation in orientation estimation

.github/workflows/builds.yml
This PR:
- Add windows to build CI job matrix (without the html extension - because can't installed on CI)
=> [CI] Add windows to build ci jobs
