mindee/doctr

- CONTRIBUTING.md
- README.md
- docs/source/installing.rst
- doctr/documents/elements.py
- doctr/models/core.py
- doctr/models/detection/core.py
- doctr/models/detection/differentiable_binarization.py
- doctr/models/preprocessor.py
- doctr/models/recognition/postprocessor.py
- doctr/models/recognition/sar.py
- doctr/models/utils.py
- doctr/utils/visualization.py
- setup.py
- test/test_models.py
- updated references to the repo location
- removed unused import & variables
> refactor: Reflected repo changes

- README.md
This PR fixes the Codefactor badge which seemed to require time before the org change propagated.
> docs: Fixed Codefactor badge

- .github/workflows/doc-status.yaml
- .github/workflows/gh-page.yaml
- .github/workflows/pkg-upload.yaml
- README.md
- renamed doc status check job
- switched CI job status
- Added doc status badge in README
- Added documentation section in readme
> docs: Updated CI badges

- doctr/models/recognition/postprocessor.py
This PR simply removes an unused import from the recognition post processing
> refactor: Removed unused import

- doctr/documents/reader.py
- test/conftest.py
- test/test_documents_reader.py
- added the possibility to read a PDF from a byte stream
- added corresponding unittest
> feat: Added PDF reading from binary stream

- doctr/utils/visualization.py
- test/test_utils_visualization.py
- removes the dependency of doctr.documents in doctr.utils by using the export dict of page to plot them
- updates unittest
Successfully merging this PR will close #57 
> refactor: Refactored visualization

- doctr/models/detection/differentiable_binarization.py
- doctr/models/recognition/crnn.py
Changed default cfg for both dbnet and crnn according to weights uploaded on the v0.1 tag.
> Refactor: changed default cfg for both DBnet & CRNN

- doctr/models/detection/differentiable_binarization.py
- doctr/models/recognition/crnn.py
- doctr/models/zoo.py
- scripts/analyze.py
- test/test_models.py
- added pretrained models for detection and recognition
- added example script
- added end-to-end predictor
Successfully merging this PR will close #53 
> feat: Added pretrained models for full end-to-end OCR

- README.md
- docs/source/models.rst
- updated README
- added predictor to documentation
This is a follow-up on #85
> docs: Added predictor to documentation

- doctr/models/core.py
- test/test_models.py
- refactors document building into a separate class for clearer reading and debugging
- added extensive unittests to fine-tune document building behaviour
> refactor: Refactored document building

- test/test_documents_elements.py
This PR simply removes an unused import in tests
> test: Removed unused import

- README.md
- scripts/analyze.py
- added instructions to use analysis script in the README
- improved script error message
> docs: Added example script instructions in README

- docs/source/index.rst
- docs/source/utils.rst
This PR simply adds documentation building for the utils module.
> docs: Added documentation of utils module

- doctr/models/detection/__init__.py
- doctr/models/detection/zoo.py
- doctr/models/recognition/__init__.py
- doctr/models/recognition/zoo.py
- doctr/models/zoo.py
- test/test_models_detection.py
- test/test_models_recognition.py
- added a zoo for detection predictors
- added a zoo for recognition predictors
- refactored OCR zoo using subtask predictors
> feat: Added detection and recognition zoo

- docs/source/models.rst
- doctr/models/recognition/zoo.py
- doctr/models/zoo.py
- split up the subtasks in the documentation
- added explanation about the operations performed in preprocessing
- added subtask zoo
- fixed docstrings
> docs: Improved documentation of doctr.models

- scripts/analyze.py
This PR simply fixes the analysis script
> fix: Fixed analysis script

- test/test_models.py
This PR simply adds a unittest for crop extraction
> test: Added unittest  for crop extraction

- doctr/models/recognition/crnn.py
- doctr/models/recognition/sar.py
This PR adds new default url in crnn cfgs
> add: default url crnn

- README.md
- docs/source/installing.rst
- setup.py
- update package version and package setup
- added pypi badge and updated installation instructions in README
- update installation instructions in documentation
> chore: Post release modifications

- docs/source/utils.rst
- doctr/utils/metrics.py
- requirements.txt
- setup.py
- test/test_utils_metrics.py
This implements end to end OCR metric as described in issue #109 [in this comment](https://github.com/mindee/doctr/issues/109#issuecomment-792617669)
Any feedback is welcome !
> feat: add end-to-end OCR metric

- .github/ISSUE_TEMPLATE/bug_report.md
- scripts/collect_env.py
This PR updates the environment collection script and the bug report.
> chore: Updated environment collection

- docs/source/datasets.rst
- docs/source/index.rst
- doctr/datasets/__init__.py
- doctr/datasets/core.py
- doctr/datasets/funsd.py
- doctr/models/utils.py
- test/test_datasets.py
- test/test_datasets_utils.py
Following up on #124, this PR introduces the following modifications:
- added an abstract VisionDataset class
- added the FUNSD dataset inherited from VisionDataset
- added it to the documentation
- refactored verified file downloading functions to use it both for model and dataset downloading
> feat: Added FUNSD dataset

- .github/workflows/main.yml
- scripts/analyze.py
- added a non blocking viz option in analysis script (to avoid blocking the CI)
- added a CI job to run the analysis script on a simple 1-page pdf
> chore: Added a CI job to check that analysis script works

- doctr/datasets/funsd.py
- doctr/utils/metrics.py
- mypy.ini
- scripts/analyze.py
- scripts/evaluate.py
- test/test_datasets.py
Following up on #124, this PR introduces the following modifications:
- added image reading in the dataset indexing method
- updated FUNSD unittest
- renamed metric args
- enabled GPU on analyze script
- added evaluation script
> feat: Added evaluation script

- doctr/models/_utils.py
- scripts/evaluate.py
- test/test_models.py
Following up on #124, this PR introduces the following modifications:
- extended support of crop extraction to absolute coordinates
- added detection and recognition metrics to the evaluation script
> feat: Added detection and recognition metric to the evaluation script

- .github/workflows/main.yml
- README.md
- demo/app.py
- demo/requirements.txt
- added demo app for text detection
- added app running instructions in the README
Here is how the app renders after performing text detection on a sample pdf:
> feat: Added minimal demo app for text detection

- doctr/datasets/core.py
- doctr/datasets/funsd.py
- added constructor docstring to `VisionDataset`
- fixes `FUNSD` docstring
> docs: Fixed dataset docstrings

- scripts/evaluate.py
This PR fixes the evaluation script, by looping on both subsets. The previous patching was not taking into account the different roots of both subsets.
> fix: Fixed evaluation script

- README.md
- docs/source/datasets.rst
- docs/source/installing.rst
- doctr/datasets/funsd.py
- doctr/utils/metrics.py
- removed legacy installation instructions from the documentation
- added `VisionDataset` to the documentation
- added example to `FUNSD`
- added example to metrics
- updated README installation instructions
> docs: Improved documentation

- doctr/models/recognition/crnn.py
- doctr/models/recognition/sar.py
- Reverted to old checkpoints
- Fixed CRNN architecture
- Partially fixed SAR (inference going smoothly as before, but from the pretrained model, saving the weights and reloading it make inference go nuts :man_shrugging: )
> fix: Fixed pretrained models

- docs/source/datasets.rst
- doctr/datasets/__init__.py
- doctr/datasets/core.py
- doctr/datasets/funsd.py
- doctr/datasets/sroie.py
- doctr/models/utils.py
- test/test_datasets.py
- added SROIE class for a cleaned version of the original dataset (removed duplicates, images without annotation, etc.)
- added corresponding entry in the documentation
- added corresponding unittest
- added default file name downloading resolution
- fixed cache folder location in download_url
> feat: Added SROIE dataset from ICDAR2019

- README.md
- demo/app.py
- docs/source/_static/css/mindee.css
- docs/source/models.rst
- doctr/models/detection/differentiable_binarization.py
- doctr/models/detection/zoo.py
- doctr/models/recognition/crnn.py
- doctr/models/recognition/sar.py
- doctr/models/recognition/zoo.py
- doctr/models/zoo.py
- scripts/analyze.py
- scripts/evaluate.py
- test/test_models.py
- test/test_models_detection.py
- test/test_models_recognition.py
- refactored predictors
- updated unittests, documentation, usage instructions, demo app and script accordingly
- fixed description of `pretrained` argument in models
- expanded content width in documentation
- added License & Contributing hyperlinks in README
> refactor: Refactored task predictors

- README.md
- doctr/documents/elements.py
- doctr/utils/visualization.py
- test/test_documents_elements.py
Following up on #173, this PR introduces the following modifications:
- added a `.show` method to `Page` and `Document` for a cleaner UX
- updated README, scripts and unittests accordingly
> feat: Added visualization method to Page and Documents

- demo/app.py
- updated document reading
- added support of image as uploaded file
- added detection model selector
Here is how it renders:
> feat: Added image support and model selection to demo app

- README.md
- docs/source/documents.rst
- doctr/documents/reader.py
- doctr/models/recognition/crnn.py
- rewrites the README completely
- added explanations about how we model documents
_Note to reviewer: I suggest checking the README rendering on the branch directly_
> docs: Improved README & documentation

- docs/source/datasets.rst
- doctr/datasets/utils.py
- test/test_datasets_utils.py
- added `encode_sequences` function
- added unittests
> feat: Added sequence encoding

- README.md
- demo/app.py
- doctr/documents/elements.py
- doctr/utils/visualization.py
- scripts/analyze.py
- test/test_utils_visualization.py
- adds the possibility to turn page visualization to a static version (text plotted above boxes)
- adds task visualization in the demo app
- updated demo app screenshot in readme
Here is how it renders now:
> feat: Added both localization & end-to-end visualization in demo app

- doctr/datasets/loaders/detection.py
- doctr/datasets/loaders/recognition.py
- test/test_datasets_loaders.py
Following up on #190, this PR introduces the following modifications:
- moves all file loading operations apart from images into the constructor
- updated detection dataloader signatures
- adapted unittests
> refactor: Refactored data loaders

- doctr/datasets/loader.py
- doctr/datasets/multithreading.py
- references/detection/train.py
- references/recognition/train.py
- test/test_datasets_multithreading.py
Following up on #198, this PR introduces the following modifications:
- adds a multithreading mapping function
- adds `workers` constructor arguments to dataloaders to enable multithreading
- added unittests
- updated training scripts
> feat: Added multithreading execution of data loading

- docs/source/conf.py
- docs/source/index.rst
- docs/source/transforms.rst
- doctr/__init__.py
- doctr/datasets/cord.py
- doctr/datasets/detection.py
- doctr/datasets/funsd.py
- doctr/datasets/recognition.py
- doctr/datasets/sroie.py
- doctr/transforms/__init__.py
- doctr/transforms/modules.py
- doctr/utils/repr.py
- references/detection/train.py
- references/recognition/train.py
- test/test_datasets.py
- test/test_datasets_detection.py
- test/test_datasets_recognition.py
- test/test_transforms.py
- added resizing, normalizing and lambda transformation objects (+ a composable wrapper to execute them sequentially)
- added optional sample transformation once the image is read as TF tensor
- added transforms to documentation
- updated documentation config
- updated training scripts
> feat: Added basic transformations

- doctr/transforms/modules.py
- test/test_transforms.py
This PR adds a parameter p in all transformations of the previous PR to choose the probability to apply each transformation.
For transformations with parameters (all transfo except ToGray), users can only control a range for these parameters and values are picked randomly within the range.
> feat: add random transformations

- doctr/models/detection/differentiable_binarization.py
- doctr/models/detection/linknet.py
- references/detection/README.md
- references/detection/train.py
- references/requirements.txt
- test/test_models_detection.py
- added flexible checkpoint saving to avoid overfitting
- improved console logging
> refactor: Refactored detection training script

- doctr/models/detection/differentiable_binarization.py
- doctr/models/detection/linknet.py
- references/detection/train.py
- references/recognition/train.py
- added a conditional checkpoint saving policy
- added fastprogress console bar
- updated detection model empty GT case
> refactor: Refactored the recognition training script

- doctr/datasets/detection.py
- references/detection/train.py
- references/recognition/train.py
- adds a short name alternative for the batch size arg in the reference scripts
- fixed an inplace box operation in `DetectionDataset`
> fix: Fixed inplace operation in DetectionDataset

- doctr/models/detection/differentiable_binarization.py
This PR fix the orientation of the polygon in compute_loss
> fix: DB polygon orientation

- demo/app.py
This PR fixes the segmentation map display in the demo app.
closes #216
> fix: demo app segmentation map

- README.md
- docs/source/documents.rst
- doctr/documents/reader.py
- requirements.txt
- setup.py
- test/test_documents_reader.py
- adds HTML conversion to PDF, and to rendered images
- updated usage instructions in README
- updated documentations
- updated package requirements
> feat: Added Document reading support for URLs

- doctr/utils/metrics.py
- test/test_utils_metrics.py
- fixes edge case of metric update when there are no predictions (previously it would reset IoU total to 0)
- updates unittests
> fix: Fixed localization metric update

- .gitignore
- doctr/models/detection/differentiable_binarization.py
- references/detection/train.py
- references/recognition/train.py
- adds console print of dataset information
- added option to run only the evaluation loop
- refactored training and evaluation loops
> feat: Improved training script

- doctr/documents/reader.py
- test/test_documents_reader.py
Following up on #237, this PR introduces the following modifications:
- doubled the default DPI for page rendering
- fixed import of PDF class
- added specific unittest
Resolves #232
> feat: Increased default DPI for page rendering of PDFs

- doctr/models/detection/core.py
- doctr/models/detection/linknet.py
- doctr/models/detection/zoo.py
- doctr/models/recognition/core.py
- doctr/models/recognition/zoo.py
- test/test_models_detection.py
- test/test_models_recognition.py
This PR fixes a double instantiation of postprocessors in predictors.
> refacto: postprocessor instantiation

- doctr/models/artefacts/__init__.py
- doctr/models/artefacts/barcode.py
- test/test_artefacts.py
This PR adds a BarCodeDetector implemented with Open CV in the artefacts sub-module. 
For now, only horizontal or small-rotated bar_codes are supported. 
Samples are displayed below, any feedback is welcome!
> feat: add BarCodeDetector

- .github/workflows/os-builds.yml
- README.md
- docs/source/installing.rst
- added CI jobs to run installation and analysis script for MacOS & Windows
Closes #265, resolves #264
> chore: Added CI job to build for other OS

- doctr/datasets/ocr.py
This PR adds the support for blank img in OCRDataset.Any feedback is welcome!
> feat: handle blank img in ocr datasets

- doctr/utils/visualization.py
This PR simply adds a separate option to plot artefacts in the page visualization.
> refactor: Added option to display artefacts

- README.md
- docs/source/changelog.rst
- docs/source/index.rst
- doctr/datasets/loader.py
- doctr/datasets/recognition.py
- doctr/datasets/sroie.py
- doctr/models/detection/core.py
- added changelog to documentation
- fixed typo and reorganized the landing page
- added a BibTeX reference in the README to cite the project
- removed unused imports
> docs: Added changelog to documentation and updated landing page

- README.md
> feat: display ocr results in readme

- .gitignore
- references/detection/train.py
- references/recognition/train.py
- references/requirements.txt
- made tensorboard logging optional
- added option to used pretrained model for training
- fixed metric logging
- added support of weights & biases logging
Running the following command:
```shell
python references/recognition/train.py /home/fg/Downloads/reco_samples sar_vgg16_bn -b 16 --wb
```
creates your setup on [Weights & Biases](https://wandb.ai/) and yields something similar to:
> feat: Added proper experiment tracking

- references/recognition/train.py
- scripts/evaluate.py
This PR fixes prediction unpacking from recognition models when there are none.
> fix: Fixed recognition output unpacking

- doctr/datasets/loader.py
- doctr/models/detection/core.py
- doctr/models/detection/linknet.py
- scripts/evaluate.py
This PR removes unused imports
> refactor: Removed unused imports

- references/detection/train.py
This PR fixes the unpacking of predictions in the evaluation run of the text detection reference script.
> fix: Fixed evaluation in detection script

- references/detection/train.py
- references/recognition/train.py
This PR fixes the Weight & biases configuration of the reference scripts.
> refactor: Improved the W&B config

- Dockerfile-api
- api/requirements.txt
- docker-compose.yml
- updated the minimum version of FastAPI for security
- updated docker compose using fastapi images as base
> chore: Updated API requirements for security

- .github/workflows/main.yml
- doctr/datasets/cord.py
- doctr/datasets/core.py
- doctr/datasets/multithreading.py
- doctr/datasets/utils.py
- doctr/documents/elements.py
- doctr/documents/reader.py
- doctr/models/core.py
- doctr/models/detection/core.py
- doctr/models/detection/differentiable_binarization.py
- doctr/models/detection/linknet.py
- doctr/models/recognition/core.py
- doctr/models/recognition/sar.py
- doctr/transforms/modules.py
- doctr/utils/geometry.py
- doctr/utils/metrics.py
- doctr/utils/visualization.py
- mypy.ini
- updates the mypy config
- fixes several typing annotations
- tries to fix the CI job that isn't finding all project files
I'm unsure why the CI isn't failing on that specific test yet.
> style: Fixed typing annotations

- .github/workflows/main.yml
- doctr/__init__.py
- doctr/models/__init__.py
- doctr/models/detection/__init__.py
- doctr/models/detection/differentiable_binarization_pt.py
- requirements-pt.txt
- test/pytorch/test_models_detection.py
Following up on #305, this PR introduces the following modifications:
- added implementation of DBNet (without postprocessor or loss computation so far)
- added unittests for pytorch codebase
- added CI job to run pytorch unittests
> feat: Added DBNet implementation in PyTorch

- doctr/models/__init__.py
- doctr/models/recognition/master.py
- fixed relative import in `__init__.py`
- fixed typing of MASTER model
> style: Fixed typing annotations and imports

- doctr/models/detection/differentiable_binarization/pytorch.py
This PR simply adds initialization for layers of DBNet
> feat: Added layer initialization in DBNet

- CONTRIBUTING.md
This PR updates instructions to run unittests and mypy checks.
> docs: Updated CONTRIBUTING

- CODE_OF_CONDUCT.md
This PR adds the default Code of Conduct to the repo !
> docs: Added Code of Conduct

- README.md
This PR updates the demo sample in README, any feedback is welcome
> feat: new demo sample in README

- doctr/models/__init__.py
- doctr/models/recognition/__init__.py
- doctr/models/recognition/core.py
- doctr/models/recognition/crnn/pytorch.py
- doctr/models/recognition/crnn/tensorflow.py
- doctr/models/recognition/master.py
- doctr/models/recognition/sar/__init__.py
- doctr/models/recognition/sar/pytorch.py
- doctr/models/recognition/sar/tensorflow.py
- doctr/models/recognition/zoo.py
- test/pytorch/test_models_recognition.py
- added PyTorch support of SAR
- enabled recognition & ocr zoo
- cleaned recognition config
> feat: Added PyTorch support of SAR

- test/test_documents_reader.py
This PR simply moves the test image to a release attachment to avoid connection issues with the remote location.
> test: Fixed unittest image

- doctr/models/recognition/master/pytorch.py
- doctr/models/recognition/master/tensorflow.py
- removes the decoding buffer from the returned values of `self.decode` for MASTER
- cleans up the logits computation
> refactor: Refactored MASTER logits decoding

- README.md
- docs/source/_static/css/mindee.css
- docs/source/datasets.rst
- docs/source/index.rst
- docs/source/models.rst
- adds PyTorch reference in README & documentation
- adapts the predictor description in the documentation
- updated font of documentation
Closes #341
> docs: Updated README and documentation

- README.md
- docs/source/documents.rst
- docs/source/models.rst
This PR illustrates with an example the export format  in README. Any feedback is welcome!
Closes #343
> docs: Add export example in README

- mypy.ini
This PR fixes a mypy missing import
> fix: mypy missing import

- docs/source/transforms.rst
- doctr/transforms/functional/pytorch.py
- doctr/transforms/functional/tensorflow.py
- doctr/transforms/modules/base.py
- mypy.ini
- test/pytorch/test_transforms_pt.py
- test/tensorflow/test_transforms_tf.py
This PR adds the` RandomRotate` module wrapper in `transforms.modules.base`.
linked to #352
> feat: add RandomRotate in transforms (Modules)

- references/detection/train_tensorflow.py
- references/recognition/train_tensorflow.py
This PR fixes the step count for the learning rate scheduler of both tensorflow training scripts.
> fix: step count in LR scheduler

- doctr/documents/elements.py
- test/common/test_documents_elements.py
- adds a `from_dict` class method to all elements
> feat: Added Element class method from export dict

- doctr/transforms/functional/pytorch.py
- doctr/transforms/functional/tensorflow.py
- doctr/transforms/modules/tensorflow.py
- doctr/utils/geometry.py
- test/pytorch/test_transforms_pt.py
- test/tensorflow/test_transforms_tf.py
Following up on #263, this PR introduces the following modifications:
- added support of FP16 input to all transformations
> feat: Added support of fp16 to doctr.transforms

- references/detection/utils.py
This PR adds a missing import to the detection utils of the training scripts.
> fix: Fixed missing import in detection training utils

- doctr/utils/visualization.py
- test/common/test_io_elements.py
- test/common/test_utils_visualization.py
- made some args optional
- split patch creation into two functions
- added more advanced geometry format checking
> refactor: Refactored visualization functions

- references/classification/README.md
- references/classification/train_pytorch.py
- references/classification/train_tensorflow.py
- references/classification/utils.py
- references/detection/train_pytorch.py
- references/detection/train_tensorflow.py
- references/recognition/README.md
- references/recognition/train_pytorch.py
- references/recognition/train_tensorflow.py
This PR adds training scripts for character classification.
> feat: Added character classification training scripts

- .github/workflows/references.yml
- references/recognition/README.md
As per #429, this PR introduces the following modifications:
- refactors the CI job to check character classification training
- added a CI job to check text recognition training
> chore: Added CI job to check recognition training

- docs/source/conf.py
- docs/source/datasets.rst
- docs/source/index.rst
- docs/source/installing.rst
- docs/source/utils.rst
As per #26, this PR introduces the following modifications to the documentation:
- made copyright year mention dynamic
- removed parent class documentation that isn't used by 99.99% of the users
- improved the landing page
- improved the installation page
- added documentation of `update` methods for metrics
- adds google analytics tag
> docs: Updated documentation

- setup.py
This PR simply updates the author email so that people can reach out the right person about the library support/issues/inquiries.
> chore: Updated author_email in setup

- references/classification/README.md
- references/recognition/README.md
This PR updates the instructions and examples for training references in their respective READMEs.
cc @jonathanMindee
> docs: Fixed READMEs of training scripts

- scripts/collect_env.py
This PR simply updates the environment collection script.
> refactor: Updated environment collection script

- README.md
This PR updates the instructions for page synthesis in the README that were failing.
> docs: Fixed README instruction for page synthesis

- README.md
This PR modifies the README as follows:
- updates the HF Spaces badge to the new URL (thanks @osanseviero for the transfer :pray:)
- updates the detailed instructions about the demo (both for running locally or enjoying the live demo)
> docs: Updated references to demo in README

- .gitignore
This PR simply adds checkpoint files to gitignore
> chore: Added checkpoint format to gitignore

- docs/source/utils.rst
- doctr/utils/metrics.py
- tests/common/test_utils_metrics.py
- added an object detection metric `DetectionMetric` for #593
- added the entry in the documentation
> feat: Added an object detection metric

- README.md
This PR adds a reference to our TFJS demo in the README.
Closes #431
> docs: Added TFJS demo ref in README

- references/classification/train_tensorflow.py
- references/detection/train_tensorflow.py
- references/obj_detection/train_pytorch.py
- references/recognition/train_tensorflow.py
- adds automatic worker number resolution to training scripts where it wasn't enabled
- added missing arg print to object detection script
> fix: Added automatic worker resolution to remaining training scripts

- doctr/models/builder.py
- doctr/models/recognition/master/pytorch.py
- doctr/models/recognition/master/tensorflow.py
- doctr/models/recognition/sar/pytorch.py
- doctr/models/recognition/sar/tensorflow.py
- references/detection/train_pytorch.py
- references/detection/train_tensorflow.py
- references/obj_detection/train_pytorch.py
- references/recognition/train_pytorch.py
- references/recognition/train_tensorflow.py
- changed model's methods to staticmethod when possible
- removed unused variables
> style: Cleaned codebase with Codacy hints

- doctr/models/detection/differentiable_binarization/base.py
- doctr/models/detection/differentiable_binarization/pytorch.py
- doctr/models/detection/differentiable_binarization/tensorflow.py
- doctr/models/detection/linknet/base.py
- doctr/models/detection/linknet/pytorch.py
- doctr/models/detection/linknet/tensorflow.py
- doctr/models/recognition/core.py
- doctr/models/recognition/crnn/pytorch.py
- doctr/models/recognition/crnn/tensorflow.py
- doctr/models/recognition/master/base.py
- doctr/models/recognition/master/pytorch.py
- doctr/models/recognition/master/tensorflow.py
- doctr/models/recognition/sar/pytorch.py
- doctr/models/recognition/sar/tensorflow.py
Since targets are built, and losses are computed, I figured we should update this :+1: 
> style: Renamed all compute_target to build_target

- doctr/utils/geometry.py
This PR fixes a bug in the angle computation of rotate_boxes (in utils/geometry.py)
> fix: rotate_boxes angle

- references/obj_detection/train_pytorch.py
This PR fixes the W&B logger in the training script for object detection, and renamed "iou" metric into "mean_iou".
> fix: Fixed W&B logger in object detection training script

- doctr/models/detection/differentiable_binarization/pytorch.py
This PR fixes the loss computation when the seg_mask is entirely on False.
> fix: Fixed edge cases of DB loss in PyTorch

- .github/workflows/style.yml
- .gitignore
This PR fixes one CI job name and ignores .idea files.
> ci: Fixed CI job name and ignored .idea files

- doctr/models/classification/mobilenet/pytorch.py
- doctr/models/classification/mobilenet/tensorflow.py
- references/classification/train_pytorch.py
- references/classification/train_tensorflow.py
- references/detection/train_pytorch.py
- references/detection/train_tensorflow.py
- references/obj_detection/train_pytorch.py
- references/recognition/train_pytorch.py
- references/recognition/train_tensorflow.py
- fixes output node sizing for mobile nets in TF & PyTorch (encountered problems with the script in char classification)
- adds LR finder option for all supported tasks in TensorFlow
Closes #478
> feat: Added LR Finder for TensorFlow scripts

- doctr/models/detection/differentiable_binarization/base.py
This PR fixes the `compute_target` of the DB
> fix: target DB

- doctr/models/detection/linknet/base.py
This PR fixes the linknet target computation in the case we have polygons
> fix: linknet target computation

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This PR simply updates the default labels applied to the issue templates (since we changed the labels recently).
> ci: Fixed issue templates

- demo/app.py
After #841, a small typo was introduced in the demo (call args), which caused the problem described in #804. This PR fixes this typo
Closes #804
> fix: Reverted mistake in demo

- docs/source/modules/datasets.rst
- docs/source/using_doctr/sharing_models.rst
This PR:
- adds missing entrys in vocabs docu
- fixes tab in sharing models
> [Fix]: Documentation add missing in vocabs and correct tab in sharing models

- doctr/models/recognition/sar/pytorch.py
- tests/conftest.py
This PR:
- fix for AttentionModule
- fix SARDecoder forward step
@frgfm let me know what you think :+1: 
BTW the url in conftest `mock_text_box_stream` was failing again can we upload an image for it to the repo please :sweat_smile: 
Issue:
#802
> [Fix] PyTorch SAR_Resnet31 implementation

- doctr/models/recognition/master/tensorflow.py
- doctr/models/recognition/transformer/tensorflow.py
- pyproject.toml
This PR:
- updates TF MASTER to make it Onnx exportable
- fix missing mypy override
> [Refactor] make TF master ONNX exportable / fix mypy

- doctr/datasets/cord.py
- doctr/datasets/funsd.py
- doctr/datasets/ic03.py
- doctr/datasets/sroie.py
- doctr/datasets/svt.py
This PR:
- update pre_transform for last datasets without (unification & reduce memory usage)
- ensure IC datasets are working
- filter whitespaces and non utf-8 in FUNSD and CORD
- filter sroie recognition
Issue:
#935
> [datasets] update IC / SROIE / FUNSD / CORD

- doctr/models/recognition/master/pytorch.py
- doctr/models/recognition/transformer/pytorch.py
- doctr/models/recognition/transformer/tensorflow.py
- tests/pytorch/test_models_recognition_pt.py
This PR:
- fix amp usage for master arch in both frameworks
- fix onnxruntime issue with MASTER PT  (instead of tril triu with transpose works fine)
Closes:
#789
> [FIX] MASTER AMP and onnxruntime issue with master PT

- references/recognition/README.md
Corrented cusomt-font-1.ttf to custom-font-1.ttf
> Fixed small typo in references recognition

- README.md
- docs/source/getting_started/installing.rst
This PR:
- add some information to install doctr on MacBooks with M1 chip
> [docs] install extras for MacBooks with M1 chip

- setup.py
> chore: dev version downgrade from 0.7.0 to 0.6.1

- api/README.md
- api/pyproject.toml
There was a `protobuf` issue in DocTR api. It has been fixed.
I also updated `README.md`.
> fix: :bug: `protobuf` issue in `api`

- docs/source/getting_started/installing.rst
Minor spelling error for developer was fixed.
> docs: Minor typo fix

- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
This PR:
- adds pre-commit
- updates the contriuting readme
Depends on: #1179
> [quality] Add pre-commit and update contributing guidelines

- references/classification/train_pytorch.py
- references/detection/train_pytorch.py
- references/recognition/train_pytorch.py
This PR:
- updates transforms for classification / detection and recognition to improve model robustness
Note: Especially blur + shadow looks realistic for det and reco (perspective transform should make the reco models more robust for non 'birds eye' crops)
> [PyTorch] update transforms pytorch (classification / det / rec)

- doctr/__init__.py
- doctr/datasets/datasets/base.py
- doctr/file_utils.py
- doctr/models/utils/pytorch.py
- doctr/models/utils/tensorflow.py
- tests/pytorch/test_models_utils_pt.py
- tests/tensorflow/test_models_utils_tf.py
This PR:
- moves `copy_tensor` from `file_utils.py` to model/ùtils.py`
> [quality] move copy tensor function

- docs/source/index.rst
- docs/source/using_doctr/custom_models_training.rst
This PR:
- Add page in docs with a ref to references README's for custom training and how to load custom models (which is the most frequent asked question :sweat_smile:)
> [docs] custom model load

- README.md
This PR:
- should fix the displayed images on https://pypi.org/project/python-doctr/  after the next release
#783
> [PyPi] Fix image display

- pyproject.toml
- setup.py
This PR:
- increase version to 0.7.0a0 (next release will be minor and not patch)
- add Olivier and myself  😅 also to the list of maintainers
I will cleanup the issue trackers in the next days 👍🏼 
Any feedback is welcome 🤗
> [chore] increase version and update maintainers

- pyproject.toml
This reverts commit 7cd7e69b4bb6a1ae92332caf94d18ae82fc09696.
> chore: :wrench: change `rapidfuzz` version

- Dockerfile
This PR updates the Dockerfile to leverage NVIDIA's TensorFlow container, ensuring better GPU support, changes the sources and creates a workdir.
**Changes:**
1. **Base Image Update:** 
- **Old:** `FROM python:3.8-slim`
- **New:** `FROM nvcr.io/nvidia/tensorflow:22.10.1-tf2-py3`
The base image has been updated to use NVIDIA's TensorFlow container. This change ensures that the container is optimized for GPU usage and includes all necessary dependencies for TensorFlow to utilize NVIDIA GPUs.
2. **Environment Variables:** 
- Added `ENV DOCTR_CACHE_DIR=/app/.cache` to specify a cache directory.
- Added `ENV PATH=/app/venv/bin:$PATH` to include the virtual environment's bin directory in the PATH.
3. **Working Directory:** 
- **New:** `WORKDIR /app`
The working directory has been set to `/app` …
> Update Dockerfile (GPU Support, Workdir, Permissions)

- doctr/models/recognition/master/pytorch.py
- doctr/models/recognition/master/tensorflow.py
- doctr/models/recognition/parseq/pytorch.py
- doctr/models/recognition/parseq/tensorflow.py
- doctr/models/recognition/sar/pytorch.py
- doctr/models/recognition/sar/tensorflow.py
- doctr/models/recognition/vitstr/pytorch.py
- doctr/models/recognition/vitstr/tensorflow.py
This PR:
- clip overflowing probs 
- @odulcy-mindee as mentioned
> [FIX] clip overflowing probs

- doctr/models/detection/differentiable_binarization/pytorch.py
- doctr/models/detection/differentiable_binarization/tensorflow.py
- doctr/models/detection/linknet/pytorch.py
- doctr/models/detection/linknet/tensorflow.py
- doctr/models/recognition/crnn/tensorflow.py
- doctr/models/recognition/master/pytorch.py
- doctr/models/recognition/master/tensorflow.py
- doctr/models/recognition/parseq/pytorch.py
- doctr/models/recognition/parseq/tensorflow.py
- doctr/models/recognition/sar/pytorch.py
- doctr/models/recognition/sar/tensorflow.py
- doctr/models/recognition/vitstr/pytorch.py
- doctr/models/recognition/vitstr/tensorflow.py
- doctr/models/utils/pytorch.py
- doctr/models/utils/tensorflow.py
- tests/pytorch/test_models_utils_pt.py
- tests/tensorflow/test_models_utils_tf.py
As discussed :sweat_smile: 
function renamed to avoid confusion
> [misc] rename helper function for bf16 to float32 casting

- references/detection/train_tensorflow.py
This PR:
- mostly unified augmentations to the PT counter part (same order / percentual applied values)
> [TF] unify detection augmentations

- README.md
> [Fix] Typo in README.md

- .github/workflows/style.yml
- doctr/datasets/imgur5k.py
- doctr/models/_utils.py
- doctr/models/detection/core.py
- doctr/models/detection/differentiable_binarization/base.py
- doctr/models/detection/linknet/base.py
- doctr/transforms/functional/base.py
- doctr/utils/geometry.py
- doctr/utils/metrics.py
This PR:
- fix / ignore opencv related mypy errors
- seems to be a known issue with the latest OpenCV version: https://github.com/opencv/opencv/issues/24803
@odulcy-mindee I checked the function calls and everything is fine (only switch from int to float in `fillPoly`)
Any feedback is welcome :) 
PS: I think we can remove the ignores after the next opencv / mypy patch release
> [FIX] Fix mypy errors

- doctr/models/detection/linknet/tensorflow.py
Update existing TF Linknet Resnet checkpoints. They have been trained using new augmentations from reference scripts.
> feat: :sparkles: new TF Linknet Resnet checkpoints

- docs/source/getting_started/installing.rst
This PR:
- Add install instructions to documentation for conda
Closses #1452
> [Docs] conda install doc

- .conda/meta.yaml
- .github/workflows/builds.yml
- .github/workflows/publish.yml
- README.md
- api/pyproject.toml
- docs/source/getting_started/installing.rst
- pyproject.toml
- setup.py
This PR:
- pypi images fix (hopefully)
- fix conda build 
- broken pypi changelog url fix
- version 0.8.1
> patch release 0.8.1

- doctr/models/detection/fast/pytorch.py
- doctr/models/detection/fast/tensorflow.py
This PR:
- change back to paper mentioned default pooling size
> [models] Tune FAST pooling size

- .pre-commit-config.yaml
- Makefile
- pyproject.toml
- references/classification/latency_pytorch.py
- references/classification/latency_tensorflow.py
- references/detection/latency_pytorch.py
- references/detection/latency_tensorflow.py
- references/obj_detection/latency_pytorch.py
- references/recognition/latency_pytorch.py
- references/recognition/latency_tensorflow.py
> [misc] update dev deps

- doctr/models/kie_predictor/pytorch.py
- doctr/models/kie_predictor/tensorflow.py
This PR:
- fix kie with assume_straight_pages output
> [Fix] crop orientation KIE

- docs/source/modules/models.rst
- doctr/models/classification/mobilenet/pytorch.py
- doctr/models/classification/mobilenet/tensorflow.py
- doctr/models/classification/predictor/pytorch.py
- doctr/models/classification/predictor/tensorflow.py
- doctr/models/classification/zoo.py
- tests/pytorch/test_models_classification_pt.py
- tests/tensorflow/test_models_classification_tf.py
This PR:
- Add page orientation predictor & corresponding tests
- Dedicated as page_orientation_predictor instead of a general orientation_predictor for further handling
- Part 1 of 2
- Part 2 will be the final integration into the OCRPredictor
> [orientation] Part 1: Add page orientation predictor

- doctr/models/recognition/parseq/pytorch.py
- doctr/models/recognition/parseq/tensorflow.py
- tests/pytorch/test_models_recognition_pt.py
- tests/tensorflow/test_models_recognition_tf.py
This PR:
- small fix for parseq - break isn't translated correctly so this fixes wrong decoded outputs
CC @llFireHawkll
> [FIX] parseq onnx export

- .conda/meta.yaml
- .github/workflows/builds.yml
This PR:
- function name is python_doctr not python-doctr (package name is python-doctr)
> [conda] Fix meta.yaml package function name

- doctr/datasets/loader.py
- doctr/models/preprocessor/tensorflow.py
- references/classification/train_tensorflow_character.py
- references/classification/train_tensorflow_orientation.py
- references/detection/evaluate_tensorflow.py
- references/detection/train_tensorflow.py
- references/recognition/evaluate_tensorflow.py
- references/recognition/train_tensorflow.py
This PR:
- Remove garbage TF workers -> crashes on GPU
@odulcy-mindee as discussed ^^
> [bug] remove TF multiprocessing workers

- pyproject.toml
This PR:
- Add py.typed to package
> [mypy] Add py.typed

- README.md
- api/app/schemas.py
- docs/source/using_doctr/using_models.rst
- doctr/models/builder.py
- doctr/utils/fonts.py
- tests/pytorch/test_models_zoo_pt.py
- tests/tensorflow/test_models_zoo_tf.py
This PR:
- include: #1648 
- fix mypy
- update readme with install options / minimize api snippet
> [misc] update README & fix mypy & change resolve blocks default

- docs/source/modules/datasets.rst
- doctr/datasets/vocabs.py
This PR:
- includes #1676 & #1618 (no response) - so close it afterwards
> [Datasets] Add hindi & bangla vocabs

- .conda/meta.yaml
- api/pyproject.toml
- docs/build.sh
- docs/source/_static/js/custom.js
- docs/source/changelog.rst
- setup.py
This PR:
- Add post release modifications
> [misc] post release 0.9.1

- docs/source/modules/datasets.rst
- doctr/datasets/vocabs.py
This PR:
- add Vietnamese letters
- update corresponding documentation vocab table
> [Datasets] Add Vietnamese letters

- .github/workflows/references.yml
- doctr/models/classification/magc_resnet/tensorflow.py
- doctr/models/classification/mobilenet/tensorflow.py
- doctr/models/classification/resnet/tensorflow.py
- doctr/models/classification/textnet/tensorflow.py
- doctr/models/classification/vgg/tensorflow.py
- doctr/models/classification/vit/tensorflow.py
- doctr/models/detection/differentiable_binarization/tensorflow.py
- doctr/models/detection/fast/tensorflow.py
- doctr/models/detection/linknet/tensorflow.py
- doctr/models/factory/hub.py
- doctr/models/preprocessor/tensorflow.py
- doctr/models/recognition/crnn/tensorflow.py
- doctr/models/recognition/master/tensorflow.py
- doctr/models/recognition/parseq/tensorflow.py
- doctr/models/recognition/sar/tensorflow.py
- doctr/models/recognition/vitstr/tensorflow.py
- doctr/models/utils/tensorflow.py
- references/classification/README.md
- references/classification/train_pytorch_orientation.py
- references/classification/train_tensorflow_character.py
- references/classification/train_tensorflow_orientation.py
- references/detection/README.md
- references/detection/evaluate_tensorflow.py
- references/detection/train_pytorch.py
- references/detection/train_tensorflow.py
- references/detection/utils.py
- references/recognition/README.md
- references/recognition/evaluate_tensorflow.py
- references/recognition/train_tensorflow.py
This PR:
- Move model building unified "under the hood"
- Unify train scripts
- Fix missing kwargs (training = True / False :exploding_head:)
> [TF] Move model building & unify train scripts

- demo/pt-requirements.txt
- demo/tf-requirements.txt
This PR:
- Fix missing demo dependencies
> [demo] Add missing viz dep for demo

- references/detection/train_pytorch.py
> Typo fix in train_pytorch.py

- docs/source/community/resources.rst
- docs/source/index.rst
This PR:
- Add a section to the documentation where we can reference some docTR community created resources
CC @cmoscardi
> [Docs] Add community docs

- .github/workflows/docs.yml
- docs/build.sh
- docs/source/changelog.rst
This PR:
- Fix required dependencies for older documentation versions
- Actual failing job: https://github.com/mindee/doctr/actions/runs/11889630781/job/33126583554
> [Fix] documentation deploy CI/CD job

- .github/dependabot.yml
This PR:
- Extend dependabot to keep actions updated
> [CI/CD] update Dependabot

- .github/workflows/public_docker_images.yml
This PR:
- change commit tags to versions
> [CI] public docker job - change commit tag to version

- references/detection/README.md
- references/detection/train_pytorch_ddp.py
- references/recognition/train_pytorch_ddp.py
This PR:
- Small ddp script adjustments
> [misc] Small DDP script adjustments

- docs/source/using_doctr/using_model_export.rst
This PR:
- Add small export page documentation fix
> [docs] Tiny documentation export page fix

- references/classification/README.md
- references/classification/train_pytorch_character.py
- references/classification/train_pytorch_orientation.py
- references/classification/train_tensorflow_character.py
- references/classification/train_tensorflow_orientation.py
- references/detection/README.md
- references/detection/evaluate_pytorch.py
- references/detection/evaluate_tensorflow.py
- references/detection/train_pytorch.py
- references/detection/train_pytorch_ddp.py
- references/detection/train_tensorflow.py
- references/recognition/README.md
- references/recognition/train_pytorch.py
- references/recognition/train_pytorch_ddp.py
- references/recognition/train_tensorflow.py
- references/requirements.txt
Usage of `tqdm slack` is explained [here](https://tqdm.github.io/docs/contrib.slack/#tqdm_slack-objects). You only need to set environment variables, no need to pass token and channel in args.
> feat: :sparkles: tqdm slack

- .pre-commit-config.yaml
- docs/source/using_doctr/custom_models_training.rst
This PR:
- small documentation addition to https://github.com/text2knowledge/docTR-Labeler
> [docs] Add note about labeling tool to training section

- .conda/meta.yaml
- .github/workflows/docs.yml
- .github/workflows/public_docker_images.yml
- .github/workflows/pull_requests.yml
- api/pyproject.toml
- docs/build.sh
- docs/source/_static/js/custom.js
- docs/source/changelog.rst
- setup.py
This PR:
- Apply post release changes
- Adjust cronjob to avoid massive image registry overload
- Docs are now built from torch backend
> [misc] post release v0.11.0 & public docker cron job adjustment

- references/recognition/train_pytorch.py
- references/recognition/train_pytorch_ddp.py
This PR:
- Fix duplicated forward call in pyorch recognition training scripts
> [Fix] Duplicated forward call in rec train scripts

- CONTRIBUTING.md
- docs/source/using_doctr/using_datasets.rst
- docs/source/using_doctr/using_models.rst
- doctr/datasets/loader.py
- doctr/datasets/recognition.py
- doctr/datasets/utils.py
- doctr/utils/data.py
- references/detection/README.md
- tests/common/test_core.py
- tests/common/test_utils_data.py
> [Docs] Fix typos

- docs/source/index.rst
- docs/source/modules/datasets.rst
- doctr/datasets/vocabs.py
* Re-order languages & alphabets in vocabs.py
* Re-order alphabet list in docs datasets
> [misc] re-order vocabs & associated doc by languages & script

- doctr/models/recognition/viptr/pytorch.py
This PR:
- Update viptr model docstrings
> [docs] Fix VIPTR docstring

- doctr/models/detection/differentiable_binarization/base.py
> [Docs] Fix typo in docstring

- .conda/meta.yaml
- .github/workflows/builds.yml
- .github/workflows/publish.yml
This PR:
- Fix missing dependency for opencv
> [CI/CD] Fix conda dependency issue

- .pre-commit-config.yaml
- doctr/datasets/ocr.py
- doctr/models/classification/predictor/pytorch.py
- doctr/models/recognition/parseq/pytorch.py
- tests/pytorch/test_models_recognition_pt.py
- tests/tensorflow/test_models_recognition_tf.py
This PR:
- Fix mypy issues
- Merge test case
> [misc] Fix mypy & merge test

- doctr/models/recognition/utils.py
- tests/common/test_models_recognition_utils.py
Heey, long time no see :wink: 
Apparently we missed a test case.
A test case that shouldn't happen, but real data is tricky sometimes :)
> [Fix] Fix merge of short strings

- README.md
- docs/source/using_doctr/using_models.rst
Relevant to this conversation #1892 I added a line in the README.md which explains other mac users how to accelerate with GPU
> Give instructions on how to enable GPU acceleration on apple silicon

- README.md
In reference to the [issue](https://github.com/mindee/doctr/issues/1979).
Thank you.
> Update/Fix README.md
